package com.example.appcall.presentation.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage(val code: String, val title: String, val flag: String) {
    ENGLISH("en", "English", "🇬🇧"),
    FRENCH("fr", "Français", "🇫🇷"),
    ARABIC("ar", "العربية", "🇸🇦"),
    SPANISH("es", "Español", "🇪🇸"),
    GERMAN("de", "Deutsch", "🇩🇪"),
    CHINESE("zh", "中文", "🇨🇳"),
    JAPANESE("ja", "日本語", "🇯🇵"),
    AUTO("auto", "Auto-Detect", "🌐");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
        }
    }
}

data class TranslationStrings(
    // Bottom navigation
    val navCalls: String,
    val navAssistant: String,
    val navAgenda: String,
    val navTasks: String,
    val navSettings: String,

    // Header & Titles
    val appTitle: String,
    val callsTitle: String,
    val callsSubtitle: String,
    val assistantTitle: String,
    val assistantSubtitle: String,
    val agendaTitle: String,
    val agendaSubtitle: String,
    val tasksTitle: String,
    val tasksSubtitle: String,
    val settingsTitle: String,
    val settingsSubtitle: String,

    // Summary & Calls
    val callSummary: String,
    val audioTranscript: String,
    val detectedAppointment: String,
    val validateSummary: String,
    val editSummary: String,
    val confirmAppointment: String,
    val dismissAppointment: String,
    val noSpeechDetected: String,
    val incomingCall: String,
    val outgoingCall: String,
    val dialNumber: String,
    val startCall: String,
    val contactsList: String,
    val allCalls: String,

    // Chat
    val chatPlaceholder: String,
    val sendButton: String,
    val chatGreeting: String,

    // Tasks & Agenda
    val addTask: String,
    val taskTitlePlaceholder: String,
    val noTasks: String,
    val noAppointments: String,
    val addAppointment: String,

    // Settings
    val profileTab: String,
    val advancedTab: String,
    val languageSection: String,
    val languageSubtitle: String,
    val themeSection: String,
    val themeSubtitle: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,
    val autoRecordCalls: String,
    val hqAudio: String,
    val serverUrl: String,
    val save: String,
    val logout: String
)

val EnglishStrings = TranslationStrings(
    navCalls = "Calls",
    navAssistant = "AI Assistant",
    navAgenda = "Agenda",
    navTasks = "Tasks",
    navSettings = "Settings",
    appTitle = "Intelligent Calls",
    callsTitle = "Call Intelligence",
    callsSubtitle = "PSTN Call Recording & Live Transcription",
    assistantTitle = "AI Assistant",
    assistantSubtitle = "Real-Time CRM & Telephony Intelligence",
    agendaTitle = "Agenda & Meetings",
    agendaSubtitle = "AI Extracted Calendar Events",
    tasksTitle = "Action Items",
    tasksSubtitle = "Synchronized CRM To-Do List",
    settingsTitle = "Settings",
    settingsSubtitle = "Profile, Language, Theme, VoIP & GDPR",
    callSummary = "Call Summary",
    audioTranscript = "Audio Transcript",
    detectedAppointment = "Detected Appointment",
    validateSummary = "Validate Summary",
    editSummary = "Edit Summary",
    confirmAppointment = "Confirm Meeting",
    dismissAppointment = "Dismiss",
    noSpeechDetected = "No distinct speech detected in this recording.",
    incomingCall = "Incoming Call",
    outgoingCall = "Outgoing Call",
    dialNumber = "Dial a phone number...",
    startCall = "Call",
    contactsList = "Address Book",
    allCalls = "All Calls",
    chatPlaceholder = "Ask about your calls, tasks, or contacts...",
    sendButton = "Send",
    chatGreeting = "Hello! I am your Intelligent Calls AI assistant. How can I help you today?",
    addTask = "Add Task",
    taskTitlePlaceholder = "Task description...",
    noTasks = "No tasks yet. Create one or let AI extract it from calls.",
    noAppointments = "No scheduled appointments.",
    addAppointment = "New Event",
    profileTab = "Profile & Preferences",
    advancedTab = "Advanced Settings",
    languageSection = "LANGUAGE & AI INTELLIGENCE",
    languageSubtitle = "Whisper STT, AI Summaries & Chatbot",
    themeSection = "THEME & APPEARANCE",
    themeSubtitle = "Customize visual display mode",
    themeDark = "Dark",
    themeLight = "Light",
    themeSystem = "System",
    autoRecordCalls = "Automatic Call Recording",
    hqAudio = "High Quality Audio (AAC HD)",
    serverUrl = "Server Base URL",
    save = "Save",
    logout = "Log Out"
)

val FrenchStrings = TranslationStrings(
    navCalls = "Appels",
    navAssistant = "Assistant IA",
    navAgenda = "Agenda",
    navTasks = "Tâches",
    navSettings = "Paramètres",
    appTitle = "Intelligent Calls",
    callsTitle = "Intelligence d'Appel",
    callsSubtitle = "Enregistrement PSTN & Transcription en direct",
    assistantTitle = "Assistant IA",
    assistantSubtitle = "Intelligence CRM & Téléphonie en direct",
    agendaTitle = "Agenda & Rendez-vous",
    agendaSubtitle = "Événements extraits par l'IA",
    tasksTitle = "Plan d'Action",
    tasksSubtitle = "Liste des tâches CRM synchronisées",
    settingsTitle = "Paramètres",
    settingsSubtitle = "Profil, Langue, Thème, VoIP & RGPD",
    callSummary = "Résumé de l'appel",
    audioTranscript = "Transcription audio",
    detectedAppointment = "Rendez-vous détecté",
    validateSummary = "Valider le résumé",
    editSummary = "Modifier le résumé",
    confirmAppointment = "Confirmer le RDV",
    dismissAppointment = "Ignorer",
    noSpeechDetected = "Aucune parole distincte détectée dans cet enregistrement.",
    incomingCall = "Appel Entrant",
    outgoingCall = "Appel Sortant",
    dialNumber = "Composer un numéro...",
    startCall = "Appeler",
    contactsList = "Répertoire",
    allCalls = "Tous les appels",
    chatPlaceholder = "Posez une question sur vos appels, tâches ou contacts...",
    sendButton = "Envoyer",
    chatGreeting = "Bonjour ! Je suis votre assistant Intelligent Calls. Comment puis-je vous aider ?",
    addTask = "Ajouter une tâche",
    taskTitlePlaceholder = "Description de la tâche...",
    noTasks = "Aucune tâche pour le moment.",
    noAppointments = "Aucun rendez-vous planifié.",
    addAppointment = "Nouvel événement",
    profileTab = "Profil & Préférences",
    advancedTab = "Paramètres Avancés",
    languageSection = "LANGUE & INTELLIGENCE IA",
    languageSubtitle = "Transcription Whisper, Résumés & Assistant",
    themeSection = "APPARENCE & THÈME",
    themeSubtitle = "Personnalisez le mode d'affichage",
    themeDark = "Sombre",
    themeLight = "Clair",
    themeSystem = "Système",
    autoRecordCalls = "Enregistrement automatique des appels",
    hqAudio = "Audio Haute Définition (AAC HD)",
    serverUrl = "Adresse du serveur",
    save = "Enregistrer",
    logout = "Se déconnecter"
)

val ArabicStrings = TranslationStrings(
    navCalls = "المكالمات",
    navAssistant = "المساعد الذكي",
    navAgenda = "المواعيد",
    navTasks = "المهام",
    navSettings = "الإعدادات",
    appTitle = "Intelligent Calls",
    callsTitle = "ذكاء المكالمات",
    callsSubtitle = "تسجيل المكالمات والتفريغ الصوتي الفوري",
    assistantTitle = "المساعد الذكي",
    assistantSubtitle = "معلومات فورية حول المهام والمكالمات",
    agendaTitle = "جدول المواعيد",
    agendaSubtitle = "المواعيد المستخرجة بواسطة الذكاء الاصطناعي",
    tasksTitle = "قائمة المهام",
    tasksSubtitle = "المهام والإجراءات المتزامنة",
    settingsTitle = "الإعدادات",
    settingsSubtitle = "الملف الشخصي، اللغة، المظهر، وخصوصية البيانات",
    callSummary = "ملخص المكالمة",
    audioTranscript = "تفريغ المكالمة الصوتي",
    detectedAppointment = "موعد تم اكتشافه",
    validateSummary = "اعتماد الملخص",
    editSummary = "تعديل الملخص",
    confirmAppointment = "تأكيد الموعد",
    dismissAppointment = "تجاهل",
    noSpeechDetected = "لم يتم رصد أي صوت واضح في هذا التسجيل.",
    incomingCall = "مكالمة واردة",
    outgoingCall = "مكالمة صادرة",
    dialNumber = "أدخل رقم الهاتف...",
    startCall = "اتصال",
    contactsList = "سجل جهات الاتصال",
    allCalls = "جميع المكالمات",
    chatPlaceholder = "اطرح سؤالاً عن مكالماتك، مواعيدك أو مهامك...",
    sendButton = "إرسال",
    chatGreeting = "مرحباً! أنا مساعدك الذكي لمكالمات العمل. كيف يمكنني مساعدتك اليوم؟",
    addTask = "إضافة مهمة",
    taskTitlePlaceholder = "تفاصيل المهمة...",
    noTasks = "لا توجد مهام حالياً.",
    noAppointments = "لا توجد مواعيد مسجلة.",
    addAppointment = "موعد جديد",
    profileTab = "الملف الشخصي والتفضيلات",
    advancedTab = "إعدادات متقدمة",
    languageSection = "اللغة والذكاء الاصطناعي",
    languageSubtitle = "تفريغ الصوت، تلخيص المكالمات والمساعد الذكي",
    themeSection = "المظهر والتصميم",
    themeSubtitle = "تخصيص وضع العرض المرئي",
    themeDark = "داكن",
    themeLight = "فاتح",
    themeSystem = "تلقائي",
    autoRecordCalls = "تسجيل المكالمات تلقائياً",
    hqAudio = "صوت عالي الدقة (AAC HD)",
    serverUrl = "عنوان الخادم",
    save = "حفظ",
    logout = "تسجيل الخروج"
)

val SpanishStrings = TranslationStrings(
    navCalls = "Llamadas",
    navAssistant = "Asistente IA",
    navAgenda = "Agenda",
    navTasks = "Tareas",
    navSettings = "Ajustes",
    appTitle = "Intelligent Calls",
    callsTitle = "Inteligencia de Llamadas",
    callsSubtitle = "Grabación de llamadas y transcripción en vivo",
    assistantTitle = "Asistente IA",
    assistantSubtitle = "Inteligencia telefónica y CRM en tiempo real",
    agendaTitle = "Agenda y Citas",
    agendaSubtitle = "Eventos extraídos por IA",
    tasksTitle = "Tareas",
    tasksSubtitle = "Lista de tareas sincronizadas",
    settingsTitle = "Ajustes",
    settingsSubtitle = "Perfil, Idioma, Tema, VoIP y RGPD",
    callSummary = "Resumen de la llamada",
    audioTranscript = "Transcripción de audio",
    detectedAppointment = "Cita detectada",
    validateSummary = "Validar resumen",
    editSummary = "Editar resumen",
    confirmAppointment = "Confirmar Cita",
    dismissAppointment = "Descartar",
    noSpeechDetected = "No se detectó voz clara en esta grabación.",
    incomingCall = "Llamada Entrante",
    outgoingCall = "Llamada Saliente",
    dialNumber = "Marcar un número...",
    startCall = "Llamar",
    contactsList = "Contactos",
    allCalls = "Todas las llamadas",
    chatPlaceholder = "Pregunta sobre llamadas, tareas o contactos...",
    sendButton = "Enviar",
    chatGreeting = "¡Hola! Soy tu asistente de llamadas inteligente. ¿En qué puedo ayudarte?",
    addTask = "Añadir Tarea",
    taskTitlePlaceholder = "Descripción de la tarea...",
    noTasks = "No hay tareas pendientes.",
    noAppointments = "No hay citas programadas.",
    addAppointment = "Nueva Cita",
    profileTab = "Perfil y Preferencias",
    advancedTab = "Ajustes Avanzados",
    languageSection = "IDIOMA E INTELIGENCIA IA",
    languageSubtitle = "Transcripción Whisper, Resúmenes y Asistente",
    themeSection = "TEMA Y APARIENCIA",
    themeSubtitle = "Personaliza el modo visual",
    themeDark = "Oscuro",
    themeLight = "Claro",
    themeSystem = "Sistema",
    autoRecordCalls = "Grabación automática de llamadas",
    hqAudio = "Audio de alta definición (AAC HD)",
    serverUrl = "URL del servidor",
    save = "Guardar",
    logout = "Cerrar sesión"
)

val GermanStrings = TranslationStrings(
    navCalls = "Anrufe",
    navAssistant = "KI-Assistent",
    navAgenda = "Termine",
    navTasks = "Aufgaben",
    navSettings = "Einstellungen",
    appTitle = "Intelligent Calls",
    callsTitle = "Anruf-Intelligenz",
    callsSubtitle = "Anrufaufzeichnung & Live-Transkription",
    assistantTitle = "KI-Assistent",
    assistantSubtitle = "Echtzeit-Telefonauskunft & CRM",
    agendaTitle = "Termine & Kalender",
    agendaSubtitle = "Von KI erkannte Termine",
    tasksTitle = "Aufgabenliste",
    tasksSubtitle = "Synchronisierte Aufgaben",
    settingsTitle = "Einstellungen",
    settingsSubtitle = "Profil, Sprache, Design, VoIP & DSGVO",
    callSummary = "Anrufzusammenfassung",
    audioTranscript = "Audiotranskription",
    detectedAppointment = "Erkannter Termin",
    validateSummary = "Zusammenfassung bestätigen",
    editSummary = "Bearbeiten",
    confirmAppointment = "Termin bestätigen",
    dismissAppointment = "Verwerfen",
    noSpeechDetected = "In dieser Aufnahme wurde keine deutliche Sprache erkannt.",
    incomingCall = "Eingehender Anruf",
    outgoingCall = "Ausgehender Anruf",
    dialNumber = "Telefonnummer wählen...",
    startCall = "Anrufen",
    contactsList = "Kontakte",
    allCalls = "Alle Anrufe",
    chatPlaceholder = "Fragen Sie nach Anrufen, Aufgaben oder Kontakten...",
    sendButton = "Senden",
    chatGreeting = "Hallo! Ich bin Ihr intelligenter Anruf-Assistent. Wie kann ich helfen?",
    addTask = "Aufgabe hinzufügen",
    taskTitlePlaceholder = "Aufgabenbeschreibung...",
    noTasks = "Keine Aufgaben vorhanden.",
    noAppointments = "Keine Termine geplant.",
    addAppointment = "Neuer Termin",
    profileTab = "Profil & Einstellungen",
    advancedTab = "Erweiterte Optionen",
    languageSection = "SPRACHE & KI-INTELLIGENZ",
    languageSubtitle = "Whisper-Transkription, KI-Zusammenfassung & Chatbot",
    themeSection = "DESIGN & ERSCHEINUNGSBILD",
    themeSubtitle = "Anzeigemodus anpassen",
    themeDark = "Dunkel",
    themeLight = "Hell",
    themeSystem = "System",
    autoRecordCalls = "Automatische Anrufaufnahme",
    hqAudio = "Hochwertiges Audio (AAC HD)",
    serverUrl = "Server-URL",
    save = "Speichern",
    logout = "Abmelden"
)

val ChineseStrings = TranslationStrings(
    navCalls = "通话",
    navAssistant = "AI 助理",
    navAgenda = "日程",
    navTasks = "待办",
    navSettings = "设置",
    appTitle = "Intelligent Calls",
    callsTitle = "智能通话",
    callsSubtitle = "原生通话录音与实时转写",
    assistantTitle = "AI 智能助理",
    assistantSubtitle = "实时 CRM 与通话智能分析",
    agendaTitle = "日程与预约",
    agendaSubtitle = "AI 自动提取的日历事件",
    tasksTitle = "待办事项",
    tasksSubtitle = "同步的企业任务清单",
    settingsTitle = "系统设置",
    settingsSubtitle = "个人资料、多语言、主题与数据合规",
    callSummary = "通话智能摘要",
    audioTranscript = "录音文字转写",
    detectedAppointment = "检测到的预约",
    validateSummary = "确认摘要",
    editSummary = "编辑摘要",
    confirmAppointment = "确认日程",
    dismissAppointment = "忽略",
    noSpeechDetected = "此录音中未检测到清晰语音。",
    incomingCall = "来电",
    outgoingCall = "去电",
    dialNumber = "请输入电话号码...",
    startCall = "拨打",
    contactsList = "通讯录",
    allCalls = "所有通话",
    chatPlaceholder = "询问有关通话、待办或联系人的信息...",
    sendButton = "发送",
    chatGreeting = "您好！我是您的智能通话助理。今天有什么可以帮您？",
    addTask = "新建待办",
    taskTitlePlaceholder = "任务描述...",
    noTasks = "暂无待办事项。",
    noAppointments = "暂无预约日程。",
    addAppointment = "添加日程",
    profileTab = "个人资料与偏好",
    advancedTab = "高级设置",
    languageSection = "多语言与 AI 引擎",
    languageSubtitle = "Whisper 转写、智能摘要与对话助理",
    themeSection = "外观与主题",
    themeSubtitle = "自定义界面显示模式",
    themeDark = "深色模式",
    themeLight = "浅色模式",
    themeSystem = "跟随系统",
    autoRecordCalls = "自动通话录音",
    hqAudio = "高清音频录制 (AAC HD)",
    serverUrl = "服务器地址",
    save = "保存",
    logout = "退出登录"
)

val JapaneseStrings = TranslationStrings(
    navCalls = "通話",
    navAssistant = "AI 助手",
    navAgenda = "予定",
    navTasks = "タスク",
    navSettings = "設定",
    appTitle = "Intelligent Calls",
    callsTitle = "通話インテリジェンス",
    callsSubtitle = "通話録音とリアルタイム文字起こし",
    assistantTitle = "AI アシスタント",
    assistantSubtitle = "リアルタイム CRM・通話分析",
    agendaTitle = "予定表・ミーティング",
    agendaSubtitle = "AI によって抽出されたカレンダー予定",
    tasksTitle = "タスク一覧",
    tasksSubtitle = "同期されたアクションアイテム",
    settingsTitle = "設定",
    settingsSubtitle = "プロフィール、言語、テーマ、VoIP、データ保護",
    callSummary = "通話要約",
    audioTranscript = "音声文字起こし",
    detectedAppointment = "検出された予定",
    validateSummary = "要約を承認",
    editSummary = "要約を編集",
    confirmAppointment = "予定を確定",
    dismissAppointment = "スキップ",
    noSpeechDetected = "録音から明確な音声を検出できませんでした。",
    incomingCall = "着信",
    outgoingCall = "発信",
    dialNumber = "電話番号を入力...",
    startCall = "発信",
    contactsList = "連絡先",
    allCalls = "すべての通話",
    chatPlaceholder = "通話、タスク、連絡先について質問...",
    sendButton = "送信",
    chatGreeting = "こんにちは！Intelligent Calls AI アシスタントです。何かお手伝いできますか？",
    addTask = "タスクを追加",
    taskTitlePlaceholder = "タスクの説明...",
    noTasks = "タスクはありません。",
    noAppointments = "予定はありません。",
    addAppointment = "予定を追加",
    profileTab = "プロフィールと設定",
    advancedTab = "詳細設定",
    languageSection = "言語と AI インテリジェンス",
    languageSubtitle = "Whisper 文字起こし、AI 要約、チャットボット",
    themeSection = "テーマと外観",
    themeSubtitle = "表示モードのカスタマイズ",
    themeDark = "ダーク",
    themeLight = "ライト",
    themeSystem = "システム連動",
    autoRecordCalls = "通話の自動録音",
    hqAudio = "高音質録音 (AAC HD)",
    serverUrl = "サーバー URL",
    save = "保存",
    logout = "ログアウト"
)

fun getAppStrings(languageCode: String?): TranslationStrings {
    return when (languageCode?.lowercase()?.take(2)) {
        "fr" -> FrenchStrings
        "ar" -> ArabicStrings
        "es" -> SpanishStrings
        "de" -> GermanStrings
        "zh" -> ChineseStrings
        "ja" -> JapaneseStrings
        else -> EnglishStrings
    }
}
