package com.example.appcall.presentation.theme

import java.util.Locale

enum class AppLanguage(val code: String, val title: String, val flag: String) {
    ENGLISH("en", "English", "🇬🇧"),
    FRENCH("fr", "Français", "🇫🇷"),
    ARABIC("ar", "العربية", "🇸🇦"),
    SPANISH("es", "Español", "🇪🇸"),
    GERMAN("de", "Deutsch", "🇩🇪"),
    CHINESE("zh", "中文", "🇨🇳"),
    JAPANESE("ja", "日本語", "🇯🇵"),
    AUTO("auto", "Auto-Detect", "🌐");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
        }
    }
}

data class TranslationStrings(
    // Bottom navigation
    val navCalls: String,
    val navAssistant: String,
    val navAgenda: String,
    val navTasks: String,
    val navSettings: String,

    // Header & Titles
    val appTitle: String,
    val callsTitle: String,
    val callsSubtitle: String,
    val assistantTitle: String,
    val assistantSubtitle: String,
    val agendaTitle: String,
    val agendaSubtitle: String,
    val tasksTitle: String,
    val tasksSubtitle: String,
    val settingsTitle: String,
    val settingsSubtitle: String,

    // Summary & Calls
    val callSummary: String,
    val audioTranscript: String,
    val detectedAppointment: String,
    val validateSummary: String,
    val editSummary: String,
    val confirmAppointment: String,
    val dismissAppointment: String,
    val noSpeechDetected: String,
    val loadingAnalysis: String,
    val retry: String,
    val lowConfidenceWarning: String,
    val lowConfidenceSubtitle: String,
    val incomingCall: String,
    val outgoingCall: String,
    val dialNumber: String,
    val startCall: String,
    val contactsList: String,
    val allCalls: String,
    val historyTab: String,
    val contactsTab: String,
    val aiConsentTitle: String,
    val aiConsentActive: String,
    val aiConsentInactive: String,
    val searchContactPlaceholder: String,

    // Chat
    val chatPlaceholder: String,
    val sendButton: String,
    val chatGreeting: String,
    val chatAnalyzing: String,
    val newChat: String,
    val chatHistory: String,

    // Tasks & Agenda
    val addTask: String,
    val taskTitlePlaceholder: String,
    val noTasks: String,
    val tasksHeader: String,
    val allTasksFilter: String,
    val pendingTasksFilter: String,
    val completedTasksFilter: String,
    val noAppointments: String,
    val addAppointment: String,
    val agendaHeader: String,
    val agendaClockSubtitle: String,

    // Settings
    val profileTab: String,
    val advancedTab: String,
    val languageSection: String,
    val languageSubtitle: String,
    val themeSection: String,
    val themeSubtitle: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,
    val autoRecordCalls: String,
    val hqAudio: String,
    val serverUrl: String,
    val save: String,
    val logout: String,
    val changePassword: String,
    val editProfile: String,
    val gdprVoiceExport: String,
    val gdprAllExport: String,
    val gdprDeleteVoice: String,

    // Additional Call History & Filter Keys
    val callHistoryAll: String,
    val callHistoryMissed: String,
    val callHistoryWithSummary: String,
    val callHistoryEmpty: String,
    val callHistorySynchronized: String,

    // Agenda Keys
    val planAppointment: String,
    val appointmentTitlePlaceholder: String,
    val today: String,
    val tomorrow: String,
    val afterTomorrow: String,
    val oneWeek: String,
    val calendarPicker: String,
    val dayLabel: String,
    val hourLabel: String,

    // Settings & Advanced Settings Keys
    val recordPrefsSection: String,
    val autoRecordDesc: String,
    val hdAudioWav: String,
    val hqAudioDesc: String,
    val aiEnginesSection: String,
    val aiEnginesSubtitle: String,
    val activePipeline: String,
    val saveAiApiKeys: String,
    val cloudTelephonySection: String,
    val cloudTelephonySubtitle: String,
    val shizukuSection: String,
    val serverConfigSection: String,
    val gdprSection: String,
    val exportGdpr: String,
    val deleteVoiceOnly: String,
    val deleteAccount: String,
    val testServer: String,
    val saveServer: String,
    val close: String,
    val validate: String,
    val delete: String,
    val active: String,
    val open: String,
    val noChatRecorded: String,

    // Tasks and Audio Vault Keys
    val audioVault: String,
    val noAudioRecordings: String,
    val playingAudio: String,
    val priorityLabel: String,
    val priorityUrgent: String,
    val priorityImportant: String,
    val priorityNormal: String,
    val detectedByAi: String,
    val shareRecording: String,
    val gdprVoiceConsentDesc: String,

    // Calling and Active Call Keys
    val dialCallTitle: String,
    val selectContactToCall: String,
    val noContactsFound: String,
    val connectingStatus: String,
    val onCallAiActive: String,
    val onCallPlain: String,
    val muteLabel: String,
    val unmuteLabel: String,
    val speakerLabel: String,
    val receiverLabel: String,
    val listeningStatus: String,
    val waitingForSpeech: String,
    val endCallLabel: String,
    val callDisconnected: String,
    val callError: String,

    // Advanced Settings & Inputs
    val aiSettingsDescription: String,
    val groqApiKeyLabel: String,
    val deepgramApiKeyLabel: String,
    val openAiApiKeyLabel: String,
    val sttModelLabel: String,
    val llmModelLabel: String,
    val voipSelectProviderLabel: String,
    val virtualNumberLabel: String,
    val saveVoipCredentials: String,
    val shizukuStatusConnected: String,
    val shizukuStatusRequired: String,
    val shizukuStatusStopped: String,
    val authorizeShizuku: String,
    val serverUrlLabel: String,
    val usbLocalMode: String,
    val wifiNetworkMode: String,
    val gdprNoticeText: String,
    val deleteAccountWarning: String,
    val voiceDictationNotAvailable: String,
    val firstNameLabel: String,
    val lastNameLabel: String,
    val emailLabel: String,
    val phoneLabel: String,
    val oldPasswordLabel: String,
    val newPasswordLabel: String,
    val confirmPasswordLabel: String,
    val passwordEmptyError: String,
    val passwordMismatchError: String,
    val passwordUpdatedSuccess: String,
    val profileUpdatedSuccess: String,
    val aiWelcomeMessage: String,
    val aiNewConversationStarted: String,
    val clearHistory: String,
    val clearHistoryConfirm: String,
    val recordingDeleted: String
)

val EnglishStrings = TranslationStrings(
    navCalls = "Calls",
    navAssistant = "AI Assistant",
    navAgenda = "Agenda",
    navTasks = "Tasks",
    navSettings = "Settings",
    appTitle = "Intelligent Calls",
    callsTitle = "Call Intelligence",
    callsSubtitle = "PSTN Call Recording & Live Transcription",
    assistantTitle = "AI Assistant",
    assistantSubtitle = "Real-Time CRM & Telephony Intelligence",
    agendaTitle = "Agenda & Meetings",
    agendaSubtitle = "AI Extracted Calendar Events",
    tasksTitle = "Action Items",
    tasksSubtitle = "Synchronized CRM To-Do List",
    settingsTitle = "Settings",
    settingsSubtitle = "Profile, Language, Theme, VoIP & GDPR",
    callSummary = "Call Summary",
    audioTranscript = "Audio Transcript",
    detectedAppointment = "Detected Appointment",
    validateSummary = "Validate Summary",
    editSummary = "Edit Summary",
    confirmAppointment = "Confirm Meeting",
    dismissAppointment = "Dismiss",
    noSpeechDetected = "No distinct speech detected in this recording.",
    loadingAnalysis = "Analyzing call recording with AI...",
    retry = "Retry",
    lowConfidenceWarning = "Low AI confidence on appointment detection",
    lowConfidenceSubtitle = "Please review the proposed date and details before confirming.",
    incomingCall = "Incoming Call",
    outgoingCall = "Outgoing Call",
    dialNumber = "Dial a number",
    startCall = "Call",
    contactsList = "Contacts",
    allCalls = "All Calls",
    historyTab = "History",
    contactsTab = "Contacts",
    aiConsentTitle = "AI Analysis & Voice Data Consent",
    aiConsentActive = "Voice recording and AI processing active",
    aiConsentInactive = "Voice analysis disabled (GDPR compliance)",
    searchContactPlaceholder = "Search a contact...",
    chatPlaceholder = "Ask a question about your calls...",
    sendButton = "Send",
    chatGreeting = "Hello! I am your AI call assistant. How can I assist you today?",
    chatAnalyzing = "Assistant is analyzing your calls...",
    newChat = "New Chat",
    chatHistory = "Chat History",
    addTask = "New Task",
    taskTitlePlaceholder = "e.g., Call back Marc at 0612345678...",
    noTasks = "No tasks found",
    tasksHeader = "CRITICAL ACTION ITEMS",
    allTasksFilter = "ALL",
    pendingTasksFilter = "PENDING",
    completedTasksFilter = "DONE",
    noAppointments = "No upcoming meetings detected",
    addAppointment = "Add Meeting",
    agendaHeader = "SCHEDULED APPOINTMENTS",
    agendaClockSubtitle = "Real-time clock synchronized",
    profileTab = "Profile",
    advancedTab = "Advanced Settings",
    languageSection = "LANGUAGE / LANGUE",
    languageSubtitle = "Interface & Speech Recognition Language",
    themeSection = "THEME & DISPLAY",
    themeSubtitle = "Visual Interface Preference",
    themeDark = "Dark Mode",
    themeLight = "Light Mode",
    themeSystem = "System Default",
    autoRecordCalls = "Automatic PSTN call recording",
    hqAudio = "High quality uncompressed WAV audio",
    serverUrl = "Server URL (Backend API)",
    save = "Save",
    logout = "Log Out",
    changePassword = "Change Password",
    editProfile = "Edit Profile",
    gdprVoiceExport = "Export Voice Recordings (JSON)",
    gdprAllExport = "Export Full Account Archive (JSON)",
    gdprDeleteVoice = "Delete All Voice Data (Right to be Forgotten)",
    callHistoryAll = "All Calls",
    callHistoryMissed = "Missed",
    callHistoryWithSummary = "With Summary",
    callHistoryEmpty = "No calls recorded yet",
    callHistorySynchronized = "Encrypted local & cloud history synced",
    planAppointment = "New Appointment",
    appointmentTitlePlaceholder = "e.g. Contract review meeting with Client...",
    today = "Today",
    tomorrow = "Tomorrow",
    afterTomorrow = "In 2 days",
    oneWeek = "In 1 week",
    calendarPicker = "Custom Date & Time",
    dayLabel = "Date",
    hourLabel = "Time",
    recordPrefsSection = "RECORDING & AUDIO PIPELINE",
    autoRecordDesc = "Capture and archive cellular voice streams",
    hdAudioWav = "HD WAV Audio 16kHz PCM",
    hqAudioDesc = "Optimal fidelity for Whisper STT",
    aiEnginesSection = "AI ENGINES & API CREDENTIALS",
    aiEnginesSubtitle = "Groq, Deepgram, OpenAI & Local Models",
    activePipeline = "Active Speech-to-Text Pipeline",
    saveAiApiKeys = "Save AI API Keys",
    cloudTelephonySection = "CLOUD TELEPHONY (VOIP)",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunking",
    shizukuSection = "SYSTEM PERMISSIONS & SHIZUKU",
    serverConfigSection = "BACKEND SERVER CONFIGURATION",
    gdprSection = "GDPR & DATA PRIVACY",
    exportGdpr = "Export My Data (JSON)",
    deleteVoiceOnly = "Delete Voice Recordings",
    deleteAccount = "Delete Account (Art. 17 GDPR)",
    testServer = "Test Connection",
    saveServer = "Save Configuration",
    close = "Close",
    validate = "Confirm",
    delete = "Delete",
    active = "ACTIVE",
    open = "OPEN",
    noChatRecorded = "No conversation history recorded",
    audioVault = "AUDIO VAULT",
    noAudioRecordings = "No audio recordings yet",
    playingAudio = "Playing audio...",
    priorityLabel = "Priority :",
    priorityUrgent = "URGENT",
    priorityImportant = "IMPORTANT",
    priorityNormal = "NORMAL",
    detectedByAi = "Detected by AI · Intelligent Calls",
    shareRecording = "Share Audio Recording",
    gdprVoiceConsentDesc = "Voice Data Consent",
    dialCallTitle = "Dial a Call",
    selectContactToCall = "Select a contact to initiate call :",
    noContactsFound = "No contacts found",
    connectingStatus = "Connecting...",
    onCallAiActive = "ON CALL - AI TRANSCRIPTION ACTIVE",
    onCallPlain = "ON CALL (PLAIN VoIP)",
    muteLabel = "Mute",
    unmuteLabel = "Unmute",
    speakerLabel = "Speaker",
    receiverLabel = "Receiver",
    listeningStatus = "Listening...",
    waitingForSpeech = "Waiting for speech...",
    endCallLabel = "End",
    callDisconnected = "Call Disconnected",
    callError = "Call Error",
    aiSettingsDescription = "Configure personal API keys for high-fidelity speech recognition and instant summaries :",
    groqApiKeyLabel = "Groq API Key (gsk_...)",
    deepgramApiKeyLabel = "Deepgram API Key (Nova-2 STT)",
    openAiApiKeyLabel = "OpenAI / Claude API Key (sk-...)",
    sttModelLabel = "Speech-to-Text Model (STT) :",
    llmModelLabel = "LLM Engine for Synthesis & Tasks :",
    voipSelectProviderLabel = "Select your Cloud VoIP carrier for 2-Way HD call recording and live transcription :",
    virtualNumberLabel = "Virtual Number / Caller ID (+1...)",
    saveVoipCredentials = "Save VoIP Credentials",
    shizukuStatusConnected = "Shizuku Connected (ADB Active)",
    shizukuStatusRequired = "Shizuku Detected (Permission required)",
    shizukuStatusStopped = "Shizuku Not Detected / Service stopped",
    authorizeShizuku = "Authorize Shizuku",
    serverUrlLabel = "Server URL (e.g. http://127.0.0.1:8000)",
    usbLocalMode = "USB Local",
    wifiNetworkMode = "Wi-Fi Network",
    gdprNoticeText = "In compliance with GDPR regulations, you have full access to view, export, and delete your personal data.",
    deleteAccountWarning = "Pursuant to Art. 17 of GDPR (Right to Erasure), your account, contacts, call history, audio recordings, and summaries will be permanently erased. This action is irreversible.",
    voiceDictationNotAvailable = "Voice dictation not available on this device",
    firstNameLabel = "First Name",
    lastNameLabel = "Last Name",
    emailLabel = "Email",
    phoneLabel = "Phone Number",
    oldPasswordLabel = "Old Password",
    newPasswordLabel = "New Password",
    confirmPasswordLabel = "Confirm Password",
    passwordEmptyError = "Password cannot be empty",
    passwordMismatchError = "Passwords do not match",
    passwordUpdatedSuccess = "Password updated successfully",
    profileUpdatedSuccess = "Profile updated successfully",
    aiWelcomeMessage = "Hello! I am your AI assistant. You can ask me questions across all your calls or target a specific contact.",
    aiNewConversationStarted = "New conversation started! Ask a question about your calls.",
    clearHistory = "Clear All",
    clearHistoryConfirm = "Are you sure you want to permanently erase all calls and audio recordings? This action cannot be undone (GDPR Art. 17).",
    recordingDeleted = "Recording and database entry permanently deleted"
)

val FrenchStrings = TranslationStrings(
    navCalls = "Appels",
    navAssistant = "Assistant IA",
    navAgenda = "Agenda",
    navTasks = "Tâches",
    navSettings = "Paramètres",
    appTitle = "Intelligent Calls",
    callsTitle = "Intelligence Téléphonique",
    callsSubtitle = "Enregistrement & Transcription en Direct",
    assistantTitle = "Assistant IA",
    assistantSubtitle = "Intelligence CRM & Téléphonie en Temps Réel",
    agendaTitle = "Agenda & Rendez-vous",
    agendaSubtitle = "Événements Extraits par l'IA",
    tasksTitle = "Actions à mener",
    tasksSubtitle = "Liste To-Do CRM Synchronisée",
    settingsTitle = "Paramètres",
    settingsSubtitle = "Profil, Langue, Thème, VoIP & RGPD",
    callSummary = "Synthèse d'Appel",
    audioTranscript = "Transcription Audio",
    detectedAppointment = "Rendez-vous Détecté",
    validateSummary = "Valider la Synthèse",
    editSummary = "Modifier la Synthèse",
    confirmAppointment = "Confirmer le RDV",
    dismissAppointment = "Ignorer",
    noSpeechDetected = "Aucune parole distincte détectée dans cet enregistrement.",
    loadingAnalysis = "Analyse de l'appel par l'IA en cours...",
    retry = "Réessayer",
    lowConfidenceWarning = "Confiance IA modérée sur la détection du rendez-vous",
    lowConfidenceSubtitle = "Veuillez vérifier la date et les détails avant de confirmer.",
    incomingCall = "Appel Entrant",
    outgoingCall = "Appel Sortant",
    dialNumber = "Composer un numéro",
    startCall = "Appeler",
    contactsList = "Contacts",
    allCalls = "Tous les appels",
    historyTab = "Historique",
    contactsTab = "Contacts",
    aiConsentTitle = "Consentement Analyse IA & Données Vocales",
    aiConsentActive = "Enregistrement et analyse IA activés",
    aiConsentInactive = "Analyse vocale désactivée (Conformité RGPD)",
    searchContactPlaceholder = "Rechercher un contact...",
    chatPlaceholder = "Posez une question sur vos appels...",
    sendButton = "Envoyer",
    chatGreeting = "Bonjour ! Je suis votre assistant vocal IA. Comment puis-je vous aider ?",
    chatAnalyzing = "L'assistant analyse vos appels...",
    newChat = "Nouveau Chat",
    chatHistory = "Historique",
    addTask = "Nouvelle tâche",
    taskTitlePlaceholder = "Ex: Rappeler Marc au 0612345678...",
    noTasks = "Aucune tâche enregistrée",
    tasksHeader = "ACTIONS CRITIQUES À MENER",
    allTasksFilter = "TOUT",
    pendingTasksFilter = "EN COURS",
    completedTasksFilter = "TERMINÉ",
    noAppointments = "Aucun rendez-vous à venir",
    addAppointment = "Nouveau RDV",
    agendaHeader = "RENDEZ-VOUS PLANIFIÉS",
    agendaClockSubtitle = "Horloge en temps réel synchronisée",
    profileTab = "Profil",
    advancedTab = "Paramètres Avancés",
    languageSection = "LANGUE / LANGUAGE",
    languageSubtitle = "Langue de l'interface et de transcription",
    themeSection = "THÈME & AFFICHAGE",
    themeSubtitle = "Préférence visuelle de l'interface",
    themeDark = "Mode Sombre",
    themeLight = "Mode Clair",
    themeSystem = "Système",
    autoRecordCalls = "Enregistrement automatique des appels",
    hqAudio = "Audio WAV haute qualité sans compression",
    serverUrl = "URL du serveur (Backend API)",
    save = "Enregistrer",
    logout = "Se déconnecter",
    changePassword = "Changer le mot de passe",
    editProfile = "Modifier le profil",
    gdprVoiceExport = "Exporter mes données audio (JSON)",
    gdprAllExport = "Exporter toutes mes données (Archive JSON)",
    gdprDeleteVoice = "Effacer mes enregistrements (Droit à l'oubli)",
    callHistoryAll = "Tous les appels",
    callHistoryMissed = "Manqués",
    callHistoryWithSummary = "Avec Résumé",
    callHistoryEmpty = "Aucun appel enregistré pour le moment",
    callHistorySynchronized = "Historique chiffré synchronisé",
    planAppointment = "Nouveau Rendez-vous",
    appointmentTitlePlaceholder = "Ex: Point d'avancement projet avec Marc...",
    today = "Aujourd'hui",
    tomorrow = "Demain",
    afterTomorrow = "Dans 2 jours",
    oneWeek = "Dans 1 semaine",
    calendarPicker = "Date et heure personnalisées",
    dayLabel = "Date",
    hourLabel = "Heure",
    recordPrefsSection = "PRÉFÉRENCES D'ENREGISTREMENT",
    autoRecordDesc = "Archiver automatiquement les flux vocaux",
    hdAudioWav = "Audio HD WAV 16kHz PCM",
    hqAudioDesc = "Fidélité optimale pour Whisper STT",
    aiEnginesSection = "MOTEURS IA & CLÉS D'API",
    aiEnginesSubtitle = "Groq, Deepgram, OpenAI et Modèles Locaux",
    activePipeline = "Pipeline de transcription vocale actif",
    saveAiApiKeys = "Enregistrer les clés d'API",
    cloudTelephonySection = "TÉLÉPHONIE CLOUD (VOIP)",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & Trunks SIP",
    shizukuSection = "PERMISSIONS SYSTÈME & SHIZUKU",
    serverConfigSection = "CONFIGURATION DU SERVEUR BACKEND",
    gdprSection = "CONFIDENTIALITÉ & RGPD",
    exportGdpr = "Exporter mes données (JSON)",
    deleteVoiceOnly = "Supprimer les enregistrements vocaux",
    deleteAccount = "Supprimer mon compte (Art. 17 RGPD)",
    testServer = "Tester la connexion",
    saveServer = "Enregistrer le serveur",
    close = "Fermer",
    validate = "Confirmer",
    delete = "Supprimer",
    active = "ACTIF",
    open = "OUVRIR",
    noChatRecorded = "Aucun historique de conversation",
    audioVault = "COFFRE-FORT AUDIO",
    noAudioRecordings = "Aucun enregistrement audio pour le moment",
    playingAudio = "En cours de lecture...",
    priorityLabel = "Priorité :",
    priorityUrgent = "URGENT",
    priorityImportant = "IMPORTANT",
    priorityNormal = "NORMAL",
    detectedByAi = "Détecté par IA · Intelligent Calls",
    shareRecording = "Partager l'enregistrement",
    gdprVoiceConsentDesc = "Consentement données vocales",
    dialCallTitle = "Composer un appel",
    selectContactToCall = "Sélectionnez un contact pour lancer l'appel :",
    noContactsFound = "Aucun contact enregistré",
    connectingStatus = "Connexion en cours...",
    onCallAiActive = "EN APPEL - TRANSCRIPTION IA ACTIVE",
    onCallPlain = "EN APPEL (VoIP STANDARD)",
    muteLabel = "Couper",
    unmuteLabel = "Micro",
    speakerLabel = "Haut-parleur",
    receiverLabel = "Écouteur",
    listeningStatus = "À l'écoute...",
    waitingForSpeech = "En attente de parole...",
    endCallLabel = "Raccrocher",
    callDisconnected = "Appel terminé",
    callError = "Erreur d'appel",
    aiSettingsDescription = "Renseignez vos clés d'API personnelles pour activer la transcription vocale haute fidélité et les résumés automatiques :",
    groqApiKeyLabel = "Clé API Groq (gsk_...)",
    deepgramApiKeyLabel = "Clé API Deepgram (Nova-2 STT)",
    openAiApiKeyLabel = "Clé API OpenAI / Claude (sk-...)",
    sttModelLabel = "Modèle Transcription Vocale (STT) :",
    llmModelLabel = "Moteur LLM Synthèse & RDV :",
    voipSelectProviderLabel = "Sélectionnez votre opérateur VoIP Cloud pour l'enregistrement 2-Way HD et la transcription :",
    virtualNumberLabel = "Numéro Virtuel / Passerelle (+33...)",
    saveVoipCredentials = "Enregistrer les identifiants VoIP",
    shizukuStatusConnected = "Shizuku Connecté (Permissions ADB Actives)",
    shizukuStatusRequired = "Shizuku Détecté (Permission requise)",
    shizukuStatusStopped = "Shizuku Non Détecté / Service arrêté",
    authorizeShizuku = "Autoriser Shizuku",
    serverUrlLabel = "URL du serveur (ex: http://127.0.0.1:8000)",
    usbLocalMode = "USB Local",
    wifiNetworkMode = "Wi-Fi Réseau",
    gdprNoticeText = "Conformément au RGPD, vous disposez d'un droit d'accès, d'export et d'effacement complet de vos données personnelles.",
    deleteAccountWarning = "Conformément à l'Art. 17 du RGPD (Droit à l'oubli), votre compte, tous vos contacts, appels, enregistrements et résumés seront définitivement effacés. Cette action est irréversible.",
    voiceDictationNotAvailable = "Dictée vocale non disponible sur ce terminal",
    firstNameLabel = "Prénom",
    lastNameLabel = "Nom",
    emailLabel = "Email",
    phoneLabel = "Numéro de téléphone",
    oldPasswordLabel = "Ancien mot de passe",
    newPasswordLabel = "Nouveau mot de passe",
    confirmPasswordLabel = "Confirmer le mot de passe",
    passwordEmptyError = "Le mot de passe ne peut pas être vide",
    passwordMismatchError = "Les mots de passe ne correspondent pas",
    passwordUpdatedSuccess = "Mot de passe modifié avec succès",
    profileUpdatedSuccess = "Profil mis à jour",
    aiWelcomeMessage = "Bonjour ! Je suis votre assistant IA. Vous pouvez me poser des questions sur l'ensemble de vos appels ou cibler un contact spécifique.",
    aiNewConversationStarted = "Nouvelle conversation démarrée ! Posez votre question sur l'ensemble de vos appels.",
    clearHistory = "Effacer tout",
    clearHistoryConfirm = "Êtes-vous sûr de vouloir supprimer tous les appels et leurs enregistrements ? Cette action est irréversible (RGPD Art. 17).",
    recordingDeleted = "Enregistrement et données associés supprimés"
)

val ArabicStrings = TranslationStrings(
    navCalls = "المكالمات",
    navAssistant = "المساعد الذكي",
    navAgenda = "المواعيد",
    navTasks = "المهام",
    navSettings = "الإعدادات",
    appTitle = "المكالمات الذكية",
    callsTitle = "ذكاء المكالمات",
    callsSubtitle = "تسجيل المكالمات والنسخ المباشر",
    assistantTitle = "المساعد الذكي",
    assistantSubtitle = "إدارة المكالمات والذكاء الفوري",
    agendaTitle = "المواعيد والاجتماعات",
    agendaSubtitle = "مواعيد مستخرجة بالذكاء الاصطناعي",
    tasksTitle = "قائمة المهام",
    tasksSubtitle = "مهام متزامنة تلقائياً",
    settingsTitle = "الإعدادات",
    settingsSubtitle = "الحساب، اللغة، المظهر، وخدمات الاتصال",
    callSummary = "ملخص المكالمة",
    audioTranscript = "النص الصوتي",
    detectedAppointment = "موعد مكتشف",
    validateSummary = "تأكيد الملخص",
    editSummary = "تعديل الملخص",
    confirmAppointment = "تأكيد الموعد",
    dismissAppointment = "تجاهل",
    noSpeechDetected = "لم يتم اكتشاف كلام واضح في هذا التسجيل.",
    loadingAnalysis = "جارٍ تحليل المكالمة بالذكاء الاصطناعي...",
    retry = "إعادة المحاولة",
    lowConfidenceWarning = "دقة الموعد المستخرج متوسطة",
    lowConfidenceSubtitle = "يرجى مراجعة التاريخ والتفاصيل قبل التأكيد.",
    incomingCall = "مكالمة واردة",
    outgoingCall = "مكالمة صادرة",
    dialNumber = "طلب رقم",
    startCall = "اتصال",
    contactsList = "جهات الاتصال",
    allCalls = "جميع المكالمات",
    historyTab = "السجل",
    contactsTab = "الأسماء",
    aiConsentTitle = "الموافقة على التحليل الصوتي والخصوصية",
    aiConsentActive = "التسجيل وتحليل الذكاء الاصطناعي مفعّل",
    aiConsentInactive = "التحليل الصوتي معطل",
    searchContactPlaceholder = "بحث عن جهة اتصال...",
    chatPlaceholder = "اطرح سؤالاً حول مكالماتك...",
    sendButton = "إرسال",
    chatGreeting = "مرحباً! أنا مساعدك الذكي للمكالمات. كيف أستطيع مساعدتك؟",
    chatAnalyzing = "المساعد يقوم بتحليل مكالماتك...",
    newChat = "محادثة جديدة",
    chatHistory = "سجل المحادثات",
    addTask = "مهمة جديدة",
    taskTitlePlaceholder = "مثال: الاتصال بـ عمر على الرقم...",
    noTasks = "لا توجد مهام مسجلة",
    tasksHeader = "المهام والإجراءات الهامة",
    allTasksFilter = "الكل",
    pendingTasksFilter = "قيد التنفيذ",
    completedTasksFilter = "مكتملة",
    noAppointments = "لا توجد مواعيد قادمة",
    addAppointment = "موعد جديد",
    agendaHeader = "المواعيد المجدولة",
    agendaClockSubtitle = "الساعة متزامنة في الوقت الفعلي",
    profileTab = "الملف الشخصي",
    advancedTab = "إعدادات متقدمة",
    languageSection = "اللغة / LANGUAGE",
    languageSubtitle = "لغة واجهة التطبيق والتعرف على الصوت",
    themeSection = "المظهر والعرض",
    themeSubtitle = "تخصيص مظهر الواجهة",
    themeDark = "الوضع الداكن",
    themeLight = "الوضع الفاتح",
    themeSystem = "تلقائي حسب النظام",
    autoRecordCalls = "تسجيل المكالمات تلقائياً",
    hqAudio = "صوت عالي الدقة بدون ضغط WAV",
    serverUrl = "رابط الخادم (API)",
    save = "حفظ",
    logout = "تسجيل الخروج",
    changePassword = "تغيير كلمة المرور",
    editProfile = "تعديل الملف الشخصي",
    gdprVoiceExport = "تصدير التسجيلات الصوتية (JSON)",
    gdprAllExport = "تصدير الأرشيف الكامل (JSON)",
    gdprDeleteVoice = "حذف التسجيلات الصوتية (حق النسيان)",
    callHistoryAll = "جميع المكالمات",
    callHistoryMissed = "الفائتة",
    callHistoryWithSummary = "مع ملخص",
    callHistoryEmpty = "لا توجد مكالمات مسجلة بعد",
    callHistorySynchronized = "سجل المكالمات مشفر ومتزامن",
    planAppointment = "موعد جديد",
    appointmentTitlePlaceholder = "مثال: مراجعة العقد مع العميل...",
    today = "اليوم",
    tomorrow = "غداً",
    afterTomorrow = "بعد يومين",
    oneWeek = "بعد أسبوع",
    calendarPicker = "تاريخ ووقت مخصص",
    dayLabel = "التاريخ",
    hourLabel = "الوقت",
    recordPrefsSection = "إعدادات التسجيل الصوتي",
    autoRecordDesc = "التقاط وتخزين التسجيلات الصوتية",
    hdAudioWav = "صوت عالي الجودة WAV 16kHz PCM",
    hqAudioDesc = "دقة مثالية لنماذج Whisper STT",
    aiEnginesSection = "محركات الذكاء الاصطناعي والمفاتيح",
    aiEnginesSubtitle = "Groq, Deepgram, OpenAI والنماذج المحلية",
    activePipeline = "مسار تحويل الصوت إلى نص المفعّل",
    saveAiApiKeys = "حفظ مفاتيح الذكاء الاصطناعي",
    cloudTelephonySection = "الاتصالات السحابية (VoIP)",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage وخطوط SIP",
    shizukuSection = "صلاحيات النظام وخدمة Shizuku",
    serverConfigSection = "إعدادات خادم التطبيق",
    gdprSection = "الخصوصية وحماية البيانات (GDPR)",
    exportGdpr = "تصدير بياناتي (JSON)",
    deleteVoiceOnly = "حذف التسجيلات الصوتية",
    deleteAccount = "حذف الحساب نهائياً",
    testServer = "اختبار الاتصال",
    saveServer = "حفظ إعدادات الخادم",
    close = "إغلاق",
    validate = "تأكيد",
    delete = "حذف",
    active = "نشط",
    open = "فتح",
    noChatRecorded = "لا يوجد سجل محادثات سابقة",
    audioVault = "خزينة التسجيلات الصوتية",
    noAudioRecordings = "لا توجد تسجيلات صوتية حالياً",
    playingAudio = "جارٍ تشغيل الصوت...",
    priorityLabel = "الأولوية :",
    priorityUrgent = "عاجل",
    priorityImportant = "هام",
    priorityNormal = "عادي",
    detectedByAi = "تم الاكتشاف بواسطة الذكاء الاصطناعي",
    shareRecording = "مشاركة التسجيل الصوتي",
    gdprVoiceConsentDesc = "الموافقة على البيانات الصوتية",
    dialCallTitle = "إجراء مكالمة",
    selectContactToCall = "اختر جهة اتصال لبدء المكالمة :",
    noContactsFound = "لم يتم العثور على جهات اتصال",
    connectingStatus = "جارٍ الاتصال...",
    onCallAiActive = "مكالمة جارية - النسخ الذكي مفعّل",
    onCallPlain = "مكالمة جارية (اتصال عادي)",
    muteLabel = "كتم",
    unmuteLabel = "تشغيل",
    speakerLabel = "مكبر الصوت",
    receiverLabel = "سماعة الأذن",
    listeningStatus = "جارٍ الاستماع...",
    waitingForSpeech = "بانتظار التحدث...",
    endCallLabel = "إنهاء",
    callDisconnected = "تم إنهاء المكالمة",
    callError = "خطأ في المكالمة",
    aiSettingsDescription = "أدخل مفاتيح API الخاصة بك لتفعيل التعرف الصوتي عالي الدقة والتلخيص الفوري :",
    groqApiKeyLabel = "مفتاح Groq API (gsk_...)",
    deepgramApiKeyLabel = "مفتاح Deepgram API (Nova-2)",
    openAiApiKeyLabel = "مفتاح OpenAI / Claude API (sk-...)",
    sttModelLabel = "نموذج تحويل الصوت إلى نص (STT) :",
    llmModelLabel = "محرك LLM للملخصات والمواعيد :",
    voipSelectProviderLabel = "اختر مزود الاتصال السحابي لتسجيل المكالمات بدقة HD :",
    virtualNumberLabel = "الرقم الافتراضي (+1...)",
    saveVoipCredentials = "حفظ بيانات مزود الاتصال",
    shizukuStatusConnected = "Shizuku متصل (صلاحيات ADB نشطة)",
    shizukuStatusRequired = "Shizuku مكتشف (يلزم منح الصلاحية)",
    shizukuStatusStopped = "Shizuku غير مكتشف / الخدمة متوقفة",
    authorizeShizuku = "منح صلاحية Shizuku",
    serverUrlLabel = "رابط الخادم (مثال: http://127.0.0.1:8000)",
    usbLocalMode = "محلي USB",
    wifiNetworkMode = "شبكة Wi-Fi",
    gdprNoticeText = "وفقاً للائحة حماية البيانات العامة (GDPR)، يحق لك الوصول إلى جميع بياناتك الشخصية وتصديرها وحذفها.",
    deleteAccountWarning = "وفقاً للمادة 17 من اللائحة العامة لحماية البيانات، سيتم حذف حسابك وجهات اتصالك وسجل مكالماتك وتسجيلاتك نهائياً وبشكل لا يمكن التراجع عنه.",
    voiceDictationNotAvailable = "الإملاء الصوتي غير متاح على هذا الجهاز",
    firstNameLabel = "الاسم الأول",
    lastNameLabel = "اسم العائلة",
    emailLabel = "البريد الإلكتروني",
    phoneLabel = "رقم الهاتف",
    oldPasswordLabel = "كلمة المرور القديمة",
    newPasswordLabel = "كلمة المرور الجديدة",
    confirmPasswordLabel = "تأكيد كلمة المرور",
    passwordEmptyError = "لا يمكن أن تكون كلمة المرور فارغة",
    passwordMismatchError = "كلمات المرور غير متطابقة",
    passwordUpdatedSuccess = "تم تعديل كلمة المرور بنجاح",
    profileUpdatedSuccess = "تم تحديث الملف الشخصي",
    aiWelcomeMessage = "مرحباً! أنا مساعدك الذكي. يمكنك طرح أسئلة حول جميع مكالماتك أو تحديد جهة اتصال معينة.",
    aiNewConversationStarted = "بدأت محادثة جديدة! اطرح سؤالك حول مكالماتك.",
    clearHistory = "مسح الكل",
    clearHistoryConfirm = "هل أنت متأكد من رغبتك في حذف جميع المكالمات والتسجيلات بشكل نهائي؟ هذا الإجراء لا يمكن التراجع عنه (المادة 17 RGPD).",
    recordingDeleted = "تم حذف التسجيل والبيانات نهائياً"
)

val SpanishStrings = TranslationStrings(
    navCalls = "Llamadas",
    navAssistant = "Asistente IA",
    navAgenda = "Agenda",
    navTasks = "Tareas",
    navSettings = "Ajustes",
    appTitle = "Intelligent Calls",
    callsTitle = "Inteligencia Telefónica",
    callsSubtitle = "Grabación de llamadas y transcripción en vivo",
    assistantTitle = "Asistente de IA",
    assistantSubtitle = "Inteligencia CRM y llamadas en tiempo real",
    agendaTitle = "Agenda y Citas",
    agendaSubtitle = "Eventos extraídos por IA",
    tasksTitle = "Acciones a realizar",
    tasksSubtitle = "Lista de tareas CRM sincronizada",
    settingsTitle = "Ajustes",
    settingsSubtitle = "Perfil, Idioma, Tema, VoIP y RGPD",
    callSummary = "Resumen de la llamada",
    audioTranscript = "Transcripción de audio",
    detectedAppointment = "Cita detectada",
    validateSummary = "Validar resumen",
    editSummary = "Editar resumen",
    confirmAppointment = "Confirmar cita",
    dismissAppointment = "Descartar",
    noSpeechDetected = "No se detectó voz clara en esta grabación.",
    loadingAnalysis = "Analizando la llamada con IA...",
    retry = "Reintentar",
    lowConfidenceWarning = "Confianza de IA moderada en la detección de citas",
    lowConfidenceSubtitle = "Por favor revise la fecha y los detalles antes de confirmar.",
    incomingCall = "Llamada entrante",
    outgoingCall = "Llamada saliente",
    dialNumber = "Marcar un número",
    startCall = "Llamar",
    contactsList = "Contactos",
    allCalls = "Todas las llamadas",
    historyTab = "Historial",
    contactsTab = "Contactos",
    aiConsentTitle = "Consentimiento de análisis de IA y datos de voz",
    aiConsentActive = "Grabación y análisis de IA activos",
    aiConsentInactive = "Análisis de voz desactivado (Cumplimiento RGPD)",
    searchContactPlaceholder = "Buscar un contacto...",
    chatPlaceholder = "Haz una pregunta sobre tus llamadas...",
    sendButton = "Enviar",
    chatGreeting = "¡Hola! Soy tu asistente de llamadas con IA. ¿Cómo puedo ayudarte hoy?",
    chatAnalyzing = "El asistente está analizando tus llamadas...",
    newChat = "Nuevo Chat",
    chatHistory = "Historial de Chat",
    addTask = "Nueva tarea",
    taskTitlePlaceholder = "Ej: Llamar a Marc al 0612345678...",
    noTasks = "No hay tareas registradas",
    tasksHeader = "ACCIONES CRÍTICAS",
    allTasksFilter = "TODO",
    pendingTasksFilter = "PENDIENTE",
    completedTasksFilter = "HECHO",
    noAppointments = "No hay citas próximas",
    addAppointment = "Nueva Cita",
    agendaHeader = "CITAS PROGRAMADAS",
    agendaClockSubtitle = "Reloj sincronizado en tiempo real",
    profileTab = "Perfil",
    advancedTab = "Ajustes Avanzados",
    languageSection = "IDIOMA / LANGUAGE",
    languageSubtitle = "Idioma de la interfaz y reconocimiento de voz",
    themeSection = "TEMA Y PANTALLA",
    themeSubtitle = "Preferencia visual de la interfaz",
    themeDark = "Modo Oscuro",
    themeLight = "Modo Claro",
    themeSystem = "Predeterminado del sistema",
    autoRecordCalls = "Grabación automática de llamadas",
    hqAudio = "Audio WAV sin comprimir de alta calidad",
    serverUrl = "URL del servidor (Backend API)",
    save = "Guardar",
    logout = "Cerrar sesión",
    changePassword = "Cambiar contraseña",
    editProfile = "Editar perfil",
    gdprVoiceExport = "Exportar grabaciones de voz (JSON)",
    gdprAllExport = "Exportar archivo completo (JSON)",
    gdprDeleteVoice = "Borrar grabaciones de voz (Derecho al olvido)",
    callHistoryAll = "Todas las llamadas",
    callHistoryMissed = "Perdidas",
    callHistoryWithSummary = "Con resumen",
    callHistoryEmpty = "Aún no hay llamadas registradas",
    callHistorySynchronized = "Historial cifrado sincronizado",
    planAppointment = "Nueva Cita",
    appointmentTitlePlaceholder = "Ej: Reunión de revisión con cliente...",
    today = "Hoy",
    tomorrow = "Mañana",
    afterTomorrow = "En 2 días",
    oneWeek = "En 1 semana",
    calendarPicker = "Fecha y hora personalizadas",
    dayLabel = "Fecha",
    hourLabel = "Hora",
    recordPrefsSection = "PREFERENCIAS DE GRABACIÓN",
    autoRecordDesc = "Archivar automáticamente los flujos de voz",
    hdAudioWav = "Audio HD WAV 16kHz PCM",
    hqAudioDesc = "Fidelidad óptima para Whisper STT",
    aiEnginesSection = "MOTORES DE IA Y CLAVES API",
    aiEnginesSubtitle = "Groq, Deepgram, OpenAI y Modelos Locales",
    activePipeline = "Pipeline de transcripción activo",
    saveAiApiKeys = "Guardar claves de IA",
    cloudTelephonySection = "TELEFONÍA EN LA NUBE (VOIP)",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage y SIP Trunks",
    shizukuSection = "PERMISOS DEL SISTEMA Y SHIZUKU",
    serverConfigSection = "CONFIGURACIÓN DEL SERVIDOR",
    gdprSection = "PRIVACIDAD Y RGPD",
    exportGdpr = "Exportar mis datos (JSON)",
    deleteVoiceOnly = "Eliminar grabaciones de voz",
    deleteAccount = "Eliminar cuenta (Art. 17 RGPD)",
    testServer = "Probar conexión",
    saveServer = "Guardar servidor",
    close = "Cerrar",
    validate = "Confirmar",
    delete = "Eliminar",
    active = "ACTIVO",
    open = "ABRIR",
    noChatRecorded = "No hay historial de chat registrado",
    audioVault = "BAÚL DE AUDIO",
    noAudioRecordings = "No hay grabaciones de audio aún",
    playingAudio = "Reproduciendo audio...",
    priorityLabel = "Prioridad :",
    priorityUrgent = "URGENTE",
    priorityImportant = "IMPORTANTE",
    priorityNormal = "NORMAL",
    detectedByAi = "Detectado por IA · Intelligent Calls",
    shareRecording = "Compartir grabación de audio",
    gdprVoiceConsentDesc = "Consentimiento de datos de voz",
    dialCallTitle = "Marcar una llamada",
    selectContactToCall = "Seleccione un contacto para llamar :",
    noContactsFound = "No se encontraron contactos",
    connectingStatus = "Conectando...",
    onCallAiActive = "EN LLAMADA - TRANSCRIPCIÓN IA ACTIVA",
    onCallPlain = "EN LLAMADA (VoIP estándar)",
    muteLabel = "Silenciar",
    unmuteLabel = "Micro",
    speakerLabel = "Altavoz",
    receiverLabel = "Auricular",
    listeningStatus = "Escuchando...",
    waitingForSpeech = "Esperando voz...",
    endCallLabel = "Colgar",
    callDisconnected = "Llamada finalizada",
    callError = "Error de llamada",
    aiSettingsDescription = "Configure sus claves de API personales para habilitar la transcripción de alta fidelidad y resúmenes automáticos :",
    groqApiKeyLabel = "Clave API Groq (gsk_...)",
    deepgramApiKeyLabel = "Clave API Deepgram (Nova-2 STT)",
    openAiApiKeyLabel = "Clave API OpenAI / Claude (sk-...)",
    sttModelLabel = "Modelo de Transcripción de Voz (STT) :",
    llmModelLabel = "Motor LLM para Resúmenes y Citas :",
    voipSelectProviderLabel = "Seleccione su operador VoIP en la nube para grabación 2-Way HD y transcripción :",
    virtualNumberLabel = "Número Virtual / Gateway (+34...)",
    saveVoipCredentials = "Guardar credenciales de VoIP",
    shizukuStatusConnected = "Shizuku Conectado (Permisos ADB Activos)",
    shizukuStatusRequired = "Shizuku Detectado (Permiso requerido)",
    shizukuStatusStopped = "Shizuku No Detectado / Servicio detenido",
    authorizeShizuku = "Autorizar Shizuku",
    serverUrlLabel = "URL del servidor (ej: http://127.0.0.1:8000)",
    usbLocalMode = "USB Local",
    wifiNetworkMode = "Red Wi-Fi",
    gdprNoticeText = "De conformidad con el RGPD, tiene derecho a acceder, exportar y eliminar por completo sus datos personales.",
    deleteAccountWarning = "De acuerdo con el Art. 17 del RGPD (Derecho al olvido), su cuenta, contactos, historial de llamadas, grabaciones y resúmenes se eliminarán de forma permanente e irreversible.",
    voiceDictationNotAvailable = "Dictado por voz no disponible en este dispositivo",
    firstNameLabel = "Nombre",
    lastNameLabel = "Apellido",
    emailLabel = "Correo electrónico",
    phoneLabel = "Número de teléfono",
    oldPasswordLabel = "Contraseña anterior",
    newPasswordLabel = "Nueva contraseña",
    confirmPasswordLabel = "Confirmar contraseña",
    passwordEmptyError = "La contraseña no puede estar vacía",
    passwordMismatchError = "Las contraseñas no coinciden",
    passwordUpdatedSuccess = "Contraseña modificada con éxito",
    profileUpdatedSuccess = "Perfil actualizado",
    aiWelcomeMessage = "¡Hola! Soy tu asistente de IA. Puedes hacerme preguntas sobre todas tus llamadas o seleccionar un contacto específico.",
    aiNewConversationStarted = "¡Nueva conversación iniciada! Haz tu pregunta sobre tus llamadas.",
    clearHistory = "Borrar todo",
    clearHistoryConfirm = "¿Está seguro de que desea eliminar todas las llamadas y grabaciones? Esta acción es irreversible (Art. 17 RGPD).",
    recordingDeleted = "Grabación y datos asociados eliminados permanentemente"
)

val GermanStrings = TranslationStrings(
    navCalls = "Anrufe",
    navAssistant = "KI-Assistent",
    navAgenda = "Termine",
    navTasks = "Aufgaben",
    navSettings = "Einstellungen",
    appTitle = "Intelligent Calls",
    callsTitle = "Anruf-Intelligenz",
    callsSubtitle = "Anrufaufzeichnung & Live-Transkription",
    assistantTitle = "KI-Assistent",
    assistantSubtitle = "Echtzeit-CRM & Telefonie-Intelligenz",
    agendaTitle = "Termine & Kalender",
    agendaSubtitle = "KI-extrahierte Kalenderereignisse",
    tasksTitle = "Aufgabenliste",
    tasksSubtitle = "Synchronisierte CRM To-Do-Liste",
    settingsTitle = "Einstellungen",
    settingsSubtitle = "Profil, Sprache, Design, VoIP & DSGVO",
    callSummary = "Anruf-Zusammenfassung",
    audioTranscript = "Audio-Transkript",
    detectedAppointment = "Erkannter Termin",
    validateSummary = "Zusammenfassung bestätigen",
    editSummary = "Zusammenfassung bearbeiten",
    confirmAppointment = "Termin bestätigen",
    dismissAppointment = "Verwerfen",
    noSpeechDetected = "Keine deutliche Sprache in dieser Aufnahme erkannt.",
    loadingAnalysis = "Anruf wird von KI analysiert...",
    retry = "Wiederholen",
    lowConfidenceWarning = "Moderate KI-Genauigkeit bei Terminerkennung",
    lowConfidenceSubtitle = "Bitte überprüfen Sie Datum und Details vor der Bestätigung.",
    incomingCall = "Eingehender Anruf",
    outgoingCall = "Ausgehender Anruf",
    dialNumber = "Nummer wählen",
    startCall = "Anrufen",
    contactsList = "Kontakte",
    allCalls = "Alle Anrufe",
    historyTab = "Verlauf",
    contactsTab = "Kontakte",
    aiConsentTitle = "Einwilligung zur KI-Analyse & Sprachdaten",
    aiConsentActive = "Aufzeichnung und KI-Verarbeitung aktiv",
    aiConsentInactive = "Sprachanalyse deaktiviert (DSGVO-konform)",
    searchContactPlaceholder = "Kontakt suchen...",
    chatPlaceholder = "Stellen Sie eine Frage zu Ihren Anrufen...",
    sendButton = "Senden",
    chatGreeting = "Hallo! Ich bin Ihr KI-Anrufassistent. Wie kann ich Ihnen heute helfen?",
    chatAnalyzing = "Assistent analysiert Ihre Anrufe...",
    newChat = "Neuer Chat",
    chatHistory = "Chat-Verlauf",
    addTask = "Neue Aufgabe",
    taskTitlePlaceholder = "z.B. Marc unter 0612345678 zurückrufen...",
    noTasks = "Keine Aufgaben gefunden",
    tasksHeader = "WICHTIGE AUFGABEN",
    allTasksFilter = "ALLE",
    pendingTasksFilter = "OFFEN",
    completedTasksFilter = "ERLEDIGT",
    noAppointments = "Keine bevorstehenden Termine",
    addAppointment = "Neuer Termin",
    agendaHeader = "GEPLANTE TERMINE",
    agendaClockSubtitle = "Echtzeit-Uhr synchronisiert",
    profileTab = "Profil",
    advancedTab = "Erweiterte Einstellungen",
    languageSection = "SPRACHE / LANGUAGE",
    languageSubtitle = "Interface- & Spracherkennungssprache",
    themeSection = "DESIGN & ANZEIGE",
    themeSubtitle = "Visuelle Darstellung",
    themeDark = "Dunkler Modus",
    themeLight = "Heller Modus",
    themeSystem = "Systemstandard",
    autoRecordCalls = "Automatische Anrufaufzeichnung",
    hqAudio = "Unkomprimiertes High-Quality WAV Audio",
    serverUrl = "Server-URL (Backend API)",
    save = "Speichern",
    logout = "Abmelden",
    changePassword = "Passwort ändern",
    editProfile = "Profil bearbeiten",
    gdprVoiceExport = "Sprachaufnahmen exportieren (JSON)",
    gdprAllExport = "Vollständiges Kontoarchiv exportieren (JSON)",
    gdprDeleteVoice = "Sprachdaten löschen (Recht auf Vergessenwerden)",
    callHistoryAll = "Alle Anrufe",
    callHistoryMissed = "Verpasst",
    callHistoryWithSummary = "Mit Zusammenfassung",
    callHistoryEmpty = "Noch keine Anrufe aufgezeichnet",
    callHistorySynchronized = "Verschlüsselter Verlauf synchronisiert",
    planAppointment = "Neuer Termin",
    appointmentTitlePlaceholder = "z.B. Projektabstimmung mit Kunde...",
    today = "Heute",
    tomorrow = "Morgen",
    afterTomorrow = "In 2 Tagen",
    oneWeek = "In 1 Woche",
    calendarPicker = "Benutzerdefiniertes Datum & Uhrzeit",
    dayLabel = "Datum",
    hourLabel = "Uhrzeit",
    recordPrefsSection = "AUFNAHME-EINSTELLUNGEN",
    autoRecordDesc = "Sprachdaten automatisch archivieren",
    hdAudioWav = "HD WAV Audio 16kHz PCM",
    hqAudioDesc = "Optimale Wiedergabetreue für Whisper STT",
    aiEnginesSection = "KI-ENGINES & API-SCHLÜSSEL",
    aiEnginesSubtitle = "Groq, Deepgram, OpenAI und Lokale Modelle",
    activePipeline = "Aktive Spracherkennungs-Pipeline",
    saveAiApiKeys = "KI-Schlüssel speichern",
    cloudTelephonySection = "CLOUD-TELEFONIE (VOIP)",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunks",
    shizukuSection = "SYSTEMBERECHTIGUNGEN & SHIZUKU",
    serverConfigSection = "SERVER-KONFIGURATION",
    gdprSection = "DATENSCHUTZ & DSGVO",
    exportGdpr = "Meine Daten exportieren (JSON)",
    deleteVoiceOnly = "Sprachaufnahmen löschen",
    deleteAccount = "Konto löschen (Art. 17 DSGVO)",
    testServer = "Verbindung testen",
    saveServer = "Server speichern",
    close = "Schließen",
    validate = "Bestätigen",
    delete = "Löschen",
    active = "AKTIV",
    open = "ÖFFNEN",
    noChatRecorded = "Kein Chat-Verlauf vorhanden",
    audioVault = "AUDIO-TRESOR",
    noAudioRecordings = "Noch keine Audioaufnahmen vorhanden",
    playingAudio = "Audio wird abgespielt...",
    priorityLabel = "Priorität :",
    priorityUrgent = "DRINGEND",
    priorityImportant = "WICHTIG",
    priorityNormal = "NORMAL",
    detectedByAi = "Von KI erkannt · Intelligent Calls",
    shareRecording = "Audioaufnahme teilen",
    gdprVoiceConsentDesc = "Einwilligung zu Sprachdaten",
    dialCallTitle = "Anruf tätigen",
    selectContactToCall = "Kontakt zum Anrufen auswählen :",
    noContactsFound = "Keine Kontakte gefunden",
    connectingStatus = "Verbindungsaufbau...",
    onCallAiActive = "IM ANRUF - KI-TRANSKRIPTION AKTIV",
    onCallPlain = "IM ANRUF (Standard VoIP)",
    muteLabel = "Stumm",
    unmuteLabel = "Mikrofon",
    speakerLabel = "Lautsprecher",
    receiverLabel = "Hörer",
    listeningStatus = "Hört zu...",
    waitingForSpeech = "Warte auf Sprache...",
    endCallLabel = "Auflegen",
    callDisconnected = "Anruf beendet",
    callError = "Anruffehler",
    aiSettingsDescription = "Geben Sie Ihre persönlichen API-Schlüssel ein, um hochpräzise Spracherkennung und Zusammenfassungen zu aktivieren :",
    groqApiKeyLabel = "Groq API-Schlüssel (gsk_...)",
    deepgramApiKeyLabel = "Deepgram API-Schlüssel (Nova-2 STT)",
    openAiApiKeyLabel = "OpenAI / Claude API-Schlüssel (sk-...)",
    sttModelLabel = "Spracherkennungsmodell (STT) :",
    llmModelLabel = "LLM-Engine für Synthese & Termine :",
    voipSelectProviderLabel = "Wählen Sie Ihren Cloud-VoIP-Anbieter für 2-Way HD-Aufnahme und Transkription :",
    virtualNumberLabel = "Virtuelle Rufnummer / Gateway (+49...)",
    saveVoipCredentials = "VoIP-Zugangsdaten speichern",
    shizukuStatusConnected = "Shizuku Verbunden (ADB-Rechte aktiv)",
    shizukuStatusRequired = "Shizuku Erkannt (Berechtigung erforderlich)",
    shizukuStatusStopped = "Shizuku Nicht erkannt / Dienst gestoppt",
    authorizeShizuku = "Shizuku autorisieren",
    serverUrlLabel = "Server-URL (z.B. http://127.0.0.1:8000)",
    usbLocalMode = "USB Lokal",
    wifiNetworkMode = "WLAN-Netzwerk",
    gdprNoticeText = "Gemäß DSGVO haben Sie das Recht auf Auskunft, Export und vollständige Löschung Ihrer personenbezogenen Daten.",
    deleteAccountWarning = "Gemäß Art. 17 DSGVO (Recht auf Löschung) werden Ihr Konto, Kontakte, Anrufverlauf, Audioaufnahmen und Zusammenfassungen dauerhaft und unwiderruflich gelöscht.",
    voiceDictationNotAvailable = "Sprachdiktat auf diesem Gerät nicht verfügbar",
    firstNameLabel = "Vorname",
    lastNameLabel = "Nachname",
    emailLabel = "E-Mail",
    phoneLabel = "Telefonnummer",
    oldPasswordLabel = "Altes Passwort",
    newPasswordLabel = "Neues Passwort",
    confirmPasswordLabel = "Passwort bestätigen",
    passwordEmptyError = "Passwort darf nicht leer sein",
    passwordMismatchError = "Passwörter stimmen nicht überein",
    passwordUpdatedSuccess = "Passwort erfolgreich geändert",
    profileUpdatedSuccess = "Profil aktualisiert",
    aiWelcomeMessage = "Hallo! Ich bin Ihr KI-Assistent. Sie können mir Fragen zu allen Ihren Anrufen stellen oder einen bestimmten Kontakt auswählen.",
    aiNewConversationStarted = "Neues Gespräch gestartet! Stellen Sie Ihre Frage zu Ihren Anrufen.",
    clearHistory = "Alles löschen",
    clearHistoryConfirm = "Möchten Sie wirklich alle Anrufe und Aufnahmen unwiderruflich löschen? (Art. 17 DSGVO).",
    recordingDeleted = "Aufnahme und Datenbankeintrag dauerhaft gelöscht"
)

val ChineseStrings = TranslationStrings(
    navCalls = "通话",
    navAssistant = "AI助手",
    navAgenda = "日程",
    navTasks = "待办",
    navSettings = "设置",
    appTitle = "Intelligent Calls",
    callsTitle = "智能通话",
    callsSubtitle = "电话录音与实时转写",
    assistantTitle = "AI助手",
    assistantSubtitle = "实时CRM与通话智能分析",
    agendaTitle = "日程与会议",
    agendaSubtitle = "AI提取的日程事件",
    tasksTitle = "待办事项",
    tasksSubtitle = "同步CRM任务清单",
    settingsTitle = "系统设置",
    settingsSubtitle = "个人资料、语言、主题与数据隐私",
    callSummary = "通话摘要",
    audioTranscript = "语音转写文本",
    detectedAppointment = "识别到的预约",
    validateSummary = "确认摘要",
    editSummary = "编辑摘要",
    confirmAppointment = "确认日程",
    dismissAppointment = "忽略",
    noSpeechDetected = "在此录音中未检测到清晰语音。",
    loadingAnalysis = "AI正在深度分析通话录音...",
    retry = "重试",
    lowConfidenceWarning = "AI对预约信息的识别置信度一般",
    lowConfidenceSubtitle = "请在确认前仔细核对日期和详细信息。",
    incomingCall = "来电",
    outgoingCall = "去电",
    dialNumber = "拨号",
    startCall = "呼叫",
    contactsList = "通讯录",
    allCalls = "所有通话",
    historyTab = "通话记录",
    contactsTab = "联系人",
    aiConsentTitle = "AI分析与语音数据授权",
    aiConsentActive = "语音录音与AI分析已开启",
    aiConsentInactive = "语音分析已停用（符合隐私合规要求）",
    searchContactPlaceholder = "搜索联系人...",
    chatPlaceholder = "询问关于您通话的问题...",
    sendButton = "发送",
    chatGreeting = "您好！我是您的智能通话助手。今天有什么我可以帮您的？",
    chatAnalyzing = "AI助手正在分析您的通话记录...",
    newChat = "新建对话",
    chatHistory = "对话历史",
    addTask = "新建待办",
    taskTitlePlaceholder = "例如：给张总回电话 13800138000...",
    noTasks = "暂无待办事项",
    tasksHeader = "重要待办事项",
    allTasksFilter = "全部",
    pendingTasksFilter = "待处理",
    completedTasksFilter = "已完成",
    noAppointments = "暂无近期预约日程",
    addAppointment = "新建预约",
    agendaHeader = "已安排日程",
    agendaClockSubtitle = "实时时钟已同步",
    profileTab = "个人资料",
    advancedTab = "高级设置",
    languageSection = "语言 / LANGUAGE",
    languageSubtitle = "界面显示语言与语音识别语言",
    themeSection = "主题与显示",
    themeSubtitle = "界面外观偏好设置",
    themeDark = "深色模式",
    themeLight = "浅色模式",
    themeSystem = "跟随系统",
    autoRecordCalls = "自动录音所有电话",
    hqAudio = "无损高保真 WAV 音频",
    serverUrl = "后端服务器接口地址",
    save = "保存",
    logout = "退出登录",
    changePassword = "修改密码",
    editProfile = "编辑资料",
    gdprVoiceExport = "导出语音录音数据 (JSON)",
    gdprAllExport = "导出完整账户归档 (JSON)",
    gdprDeleteVoice = "清除所有语音数据（被遗忘权）",
    callHistoryAll = "全部通话",
    callHistoryMissed = "未接来电",
    callHistoryWithSummary = "含AI摘要",
    callHistoryEmpty = "暂无通话记录",
    callHistorySynchronized = "本地加密与云端记录已同步",
    planAppointment = "新建预约",
    appointmentTitlePlaceholder = "例如：与客户进行项目进度会议...",
    today = "今天",
    tomorrow = "明天",
    afterTomorrow = "后天",
    oneWeek = "一周后",
    calendarPicker = "自定义日期和时间",
    dayLabel = "日期",
    hourLabel = "时间",
    recordPrefsSection = "录音与音频偏好",
    autoRecordDesc = "自动捕捉并存档蜂窝语音流",
    hdAudioWav = "高清 WAV 16kHz PCM 音频",
    hqAudioDesc = "最适合 Whisper STT 识别的音频格式",
    aiEnginesSection = "AI 引擎与 API 密钥",
    aiEnginesSubtitle = "Groq, Deepgram, OpenAI 及本地大模型",
    activePipeline = "当前启用的语音转写链路",
    saveAiApiKeys = "保存 AI 密钥配置",
    cloudTelephonySection = "云通信与网络电话 (VOIP)",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage 及 SIP 中继",
    shizukuSection = "系统权限与 SHIZUKU 服务",
    serverConfigSection = "后端服务器配置",
    gdprSection = "数据合规与隐私保护 (GDPR)",
    exportGdpr = "导出我的数据 (JSON)",
    deleteVoiceOnly = "删除所有录音文件",
    deleteAccount = "彻底注销账户 (GDPR 第17条)",
    testServer = "测试连接",
    saveServer = "保存服务器配置",
    close = "关闭",
    validate = "确认",
    delete = "删除",
    active = "运行中",
    open = "打开",
    noChatRecorded = "暂无历史对话记录",
    audioVault = "音频保险箱",
    noAudioRecordings = "暂无音频录音文件",
    playingAudio = "正在播放音频...",
    priorityLabel = "优先级 :",
    priorityUrgent = "紧急",
    priorityImportant = "重要",
    priorityNormal = "普通",
    detectedByAi = "由 AI 智能检测 · Intelligent Calls",
    shareRecording = "分享录音文件",
    gdprVoiceConsentDesc = "语音数据授权",
    dialCallTitle = "拨打电话",
    selectContactToCall = "选择联系人发起呼叫 :",
    noContactsFound = "未找到联系人",
    connectingStatus = "正在建立连接...",
    onCallAiActive = "通话中 - 实时 AI 转写已启动",
    onCallPlain = "通话中 (标准 VoIP 通话)",
    muteLabel = "静音",
    unmuteLabel = "开麦",
    speakerLabel = "扬声器",
    receiverLabel = "听筒",
    listeningStatus = "正在倾听...",
    waitingForSpeech = "等待发言...",
    endCallLabel = "挂断",
    callDisconnected = "通话已结束",
    callError = "呼叫异常",
    aiSettingsDescription = "配置您的专属 API 密钥以启用高保真语音识别与智能摘要 :",
    groqApiKeyLabel = "Groq API Key (gsk_...)",
    deepgramApiKeyLabel = "Deepgram API Key (Nova-2 STT)",
    openAiApiKeyLabel = "OpenAI / Claude API Key (sk-...)",
    sttModelLabel = "语音转文字模型 (STT) :",
    llmModelLabel = "总结与日程提取大模型 (LLM) :",
    voipSelectProviderLabel = "选择您的云 VoIP 运营商以支持双向高清录音与实时转写 :",
    virtualNumberLabel = "虚拟号码 / 主叫号码 (+86...)",
    saveVoipCredentials = "保存通信服务商凭证",
    shizukuStatusConnected = "Shizuku 已连接 (ADB 权限正常)",
    shizukuStatusRequired = "检测到 Shizuku (需要授权)",
    shizukuStatusStopped = "未检测到 Shizuku / 服务未运行",
    authorizeShizuku = "授权 Shizuku 权限",
    serverUrlLabel = "服务器地址 (例: http://127.0.0.1:8000)",
    usbLocalMode = "USB 本地",
    wifiNetworkMode = "Wi-Fi 局域网",
    gdprNoticeText = "根据数据隐私保护法规，您拥有查看、导出及彻底删除个人所有数据的完整权利。",
    deleteAccountWarning = "依据 GDPR 第 17 条（被遗忘权），您的账户、通讯录、通话记录、录音及智能摘要将被永久彻底删除，此操作无法撤销。",
    voiceDictationNotAvailable = "此设备不支持语音听写",
    firstNameLabel = "名字",
    lastNameLabel = "姓氏",
    emailLabel = "电子邮件",
    phoneLabel = "电话号码",
    oldPasswordLabel = "旧密码",
    newPasswordLabel = "新密码",
    confirmPasswordLabel = "确认密码",
    passwordEmptyError = "密码不能为空",
    passwordMismatchError = "密码不一致",
    passwordUpdatedSuccess = "密码修改成功",
    profileUpdatedSuccess = "个人资料已更新",
    aiWelcomeMessage = "您好！我是您的AI助手。您可以向我询问所有通话的详情或指定联系人。",
    aiNewConversationStarted = "新对话已开启！请输入有关通话的问题。",
    clearHistory = "清空全部",
    clearHistoryConfirm = "您确定要永久删除所有通话记录、录音及摘要吗？此操作无法撤销（GDPR 第17条）。",
    recordingDeleted = "录音及关联数据库记录已彻底删除"
)

val JapaneseStrings = TranslationStrings(
    navCalls = "通話",
    navAssistant = "AIアシスタント",
    navAgenda = "予定",
    navTasks = "タスク",
    navSettings = "設定",
    appTitle = "Intelligent Calls",
    callsTitle = "通話インテリジェンス",
    callsSubtitle = "通話録音とリアルタイム文字起こし",
    assistantTitle = "AIアシスタント",
    assistantSubtitle = "リアルタイムCRMと通話インテリジェンス",
    agendaTitle = "予定と会議",
    agendaSubtitle = "AIが自動抽出したカレンダー予定",
    tasksTitle = "アクションアイテム",
    tasksSubtitle = "同期済みCRM To-Doリスト",
    settingsTitle = "設定",
    settingsSubtitle = "アカウント、言語、テーマ、VoIP、データプライバシー",
    callSummary = "通話サマリー",
    audioTranscript = "音声書き起こし",
    detectedAppointment = "検出された予定",
    validateSummary = "サマリーを確定",
    editSummary = "サマリーを編集",
    confirmAppointment = "予定を確定",
    dismissAppointment = "スキップ",
    noSpeechDetected = "この録音には明瞭な音声が検出されませんでした。",
    loadingAnalysis = "AIによる通話分析中...",
    retry = "再試行",
    lowConfidenceWarning = "AIによる予定検出の信頼度が中程度です",
    lowConfidenceSubtitle = "確定する前に日時と詳細をご確認ください。",
    incomingCall = "着信",
    outgoingCall = "発信",
    dialNumber = "番号入力",
    startCall = "発信",
    contactsList = "連絡先",
    allCalls = "すべての通話",
    historyTab = "通話履歴",
    contactsTab = "連絡先",
    aiConsentTitle = "AI分析および音声データ利用への同意",
    aiConsentActive = "通話録音とAI処理が有効です",
    aiConsentInactive = "音声分析が無効です（プライバシー保護準拠）",
    searchContactPlaceholder = "連絡先を検索...",
    chatPlaceholder = "通話内容について質問を入力...",
    sendButton = "送信",
    chatGreeting = "こんにちは！通話AIアシスタントです。何かお手伝いできることはありますか？",
    chatAnalyzing = "通話記録を分析しています...",
    newChat = "新しい会話",
    chatHistory = "会話履歴",
    addTask = "タスク追加",
    taskTitlePlaceholder = "例: 田中様に折り返し電話 090-1234-5678...",
    noTasks = "登録されたタスクはありません",
    tasksHeader = "重要な対応タスク",
    allTasksFilter = "すべて",
    pendingTasksFilter = "未完了",
    completedTasksFilter = "完了済み",
    noAppointments = "直近の予定はありません",
    addAppointment = "予定を追加",
    agendaHeader = "スケジュール予定",
    agendaClockSubtitle = "リアルタイム同期中",
    profileTab = "プロフィール",
    advancedTab = "詳細設定",
    languageSection = "言語 / LANGUAGE",
    languageSubtitle = "アプリ表示言語および音声認識言語",
    themeSection = "テーマと表示",
    themeSubtitle = "画面デザインの設定",
    themeDark = "ダークモード",
    themeLight = "ライトモード",
    themeSystem = "システム設定に従う",
    autoRecordCalls = "通話の自動録音",
    hqAudio = "高音質非圧縮 WAV オーディオ",
    serverUrl = "サーバーURL (バックエンドAPI)",
    save = "保存",
    logout = "ログアウト",
    changePassword = "パスワード変更",
    editProfile = "プロフィール編集",
    gdprVoiceExport = "音声録音データのエクスポート (JSON)",
    gdprAllExport = "アカウント全データのエクスポート (JSON)",
    gdprDeleteVoice = "音声データの全消去（忘れられる権利）",
    callHistoryAll = "すべての通話",
    callHistoryMissed = "不在着信",
    callHistoryWithSummary = "サマリー付き",
    callHistoryEmpty = "通話履歴はありません",
    callHistorySynchronized = "暗号化された履歴が同期されています",
    planAppointment = "新しい予定",
    appointmentTitlePlaceholder = "例: クライアントとの進捗確認ミーティング...",
    today = "今日",
    tomorrow = "明日",
    afterTomorrow = "明後日",
    oneWeek = "1週間後",
    calendarPicker = "日時を指定",
    dayLabel = "日付",
    hourLabel = "時刻",
    recordPrefsSection = "録音およびオーディオ設定",
    autoRecordDesc = "通話音声を自動的に保存・アーカイブ",
    hdAudioWav = "HD WAV 16kHz PCM オーディオ",
    hqAudioDesc = "Whisper STT に最適な高品質フォーマット",
    aiEnginesSection = "AIエンジンとAPIキー",
    aiEnginesSubtitle = "Groq, Deepgram, OpenAI およびローカルモデル",
    activePipeline = "有効な音声文字起こしパイプライン",
    saveAiApiKeys = "AIキーを保存",
    cloudTelephonySection = "クラウドテレフォニー (VOIP)",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage および SIP トランク",
    shizukuSection = "システム権限と SHIZUKU",
    serverConfigSection = "サーバー設定",
    gdprSection = "プライバシーとデータ保護 (GDPR)",
    exportGdpr = "データをエクスポート (JSON)",
    deleteVoiceOnly = "音声録音を削除",
    deleteAccount = "アカウントを完全に削除 (GDPR 第17条)",
    testServer = "接続テスト",
    saveServer = "サーバー設定を保存",
    close = "閉じる",
    validate = "確認",
    delete = "削除",
    active = "有効",
    open = "開く",
    noChatRecorded = "会話履歴はありません",
    audioVault = "オーディオ保管庫",
    noAudioRecordings = "音声録音はありません",
    playingAudio = "音声を再生中...",
    priorityLabel = "優先度 :",
    priorityUrgent = "緊急",
    priorityImportant = "重要",
    priorityNormal = "通常",
    detectedByAi = "AIによって検出 · Intelligent Calls",
    shareRecording = "録音ファイルを共有",
    gdprVoiceConsentDesc = "音声データの利用同意",
    dialCallTitle = "電話をかける",
    selectContactToCall = "発信する連絡先を選択してください :",
    noContactsFound = "連絡先が見つかりません",
    connectingStatus = "接続中...",
    onCallAiActive = "通話中 - リアルタイムAI文字起こし有効",
    onCallPlain = "通話中 (標準VoIP通話)",
    muteLabel = "ミュート",
    unmuteLabel = "ミュート解除",
    speakerLabel = "スピーカー",
    receiverLabel = "受話口",
    listeningStatus = "聞き取り中...",
    waitingForSpeech = "発話を待機中...",
    endCallLabel = "通話終了",
    callDisconnected = "通話が終了しました",
    callError = "通話エラー",
    aiSettingsDescription = "高精度な音声認識と要約を有効にするため、個人のAPIキーを設定してください :",
    groqApiKeyLabel = "Groq API Key (gsk_...)",
    deepgramApiKeyLabel = "Deepgram API Key (Nova-2 STT)",
    openAiApiKeyLabel = "OpenAI / Claude API Key (sk-...)",
    sttModelLabel = "音声認識モデル (STT) :",
    llmModelLabel = "要約および予定抽出モデル (LLM) :",
    voipSelectProviderLabel = "双方向HD録音および文字起こし用のVoIP事業者を選択してください :",
    virtualNumberLabel = "仮想電話番号 / 発信元番号 (+81...)",
    saveVoipCredentials = "VoIP認証情報を保存",
    shizukuStatusConnected = "Shizuku 接続済み (ADB権限有効)",
    shizukuStatusRequired = "Shizuku 検出 (権限が必要です)",
    shizukuStatusStopped = "Shizuku 未検出 / サービス停止中",
    authorizeShizuku = "Shizuku 権限を許可",
    serverUrlLabel = "サーバーURL (例: http://127.0.0.1:8000)",
    usbLocalMode = "USB ローカル",
    wifiNetworkMode = "Wi-Fi ネットワーク",
    gdprNoticeText = "プライバシー保護規制に基づき、個人データの閲覧、エクスポート、および完全消去を行う権利があります。",
    deleteAccountWarning = "GDPR 第17条（消去権）に基づき、アカウント、連絡先、通話履歴、音声録音、およびサマリーが完全に消去されます。この操作は取り消せません。",
    voiceDictationNotAvailable = "この端末では音声入力を使用できません",
    firstNameLabel = "名",
    lastNameLabel = "姓",
    emailLabel = "メールアドレス",
    phoneLabel = "電話番号",
    oldPasswordLabel = "現在のパスワード",
    newPasswordLabel = "新しいパスワード",
    confirmPasswordLabel = "パスワード再入力",
    passwordEmptyError = "パスワードを入力してください",
    passwordMismatchError = "パスワードが一致しません",
    passwordUpdatedSuccess = "パスワードを変更しました",
    profileUpdatedSuccess = "プロフィールを更新しました",
    aiWelcomeMessage = "こんにちは！AIアシスタントです。すべての通話に関する質問や、特定の連絡先について尋ねることができます。",
    aiNewConversationStarted = "新しい会話が開始されました！通話に関する質問を入力してください。",
    clearHistory = "すべて消去",
    clearHistoryConfirm = "すべての通話履歴、音声録音、およびサマリーを完全に消去してもよろしいですか？この操作は取り消せません（GDPR 第17条）。",
    recordingDeleted = "録音およびデータベース記録が完全に削除されました"
)

fun getAppStrings(languageCode: String): TranslationStrings {
    return when (languageCode.lowercase(Locale.ROOT)) {
        "fr" -> FrenchStrings
        "ar" -> ArabicStrings
        "es" -> SpanishStrings
        "de" -> GermanStrings
        "zh" -> ChineseStrings
        "ja" -> JapaneseStrings
        "auto" -> {
            val systemLang = Locale.getDefault().language.lowercase(Locale.ROOT)
            getAppStrings(systemLang)
        }
        else -> EnglishStrings
    }
}

fun getAppLocale(languageCode: String): Locale {
    return when (languageCode.lowercase(Locale.ROOT)) {
        "fr" -> Locale.FRENCH
        "ar" -> Locale("ar")
        "es" -> Locale("es")
        "de" -> Locale.GERMAN
        "zh" -> Locale.CHINESE
        "ja" -> Locale.JAPANESE
        "auto" -> Locale.getDefault()
        else -> Locale.ENGLISH
    }
}
