# Python script to update AppStrings.kt with exhaustive localization dictionary
import os

app_strings_content = '''package com.example.appcall.presentation.theme

import java.util.Locale

enum class AppLanguage(val code: String, val title: String, val flag: String) {
    ENGLISH("en", "English", "🇬🇧"),
    FRENCH("fr", "Français", "🇫🇷"),
    ARABIC("ar", "العربية", "🇸🇦"),
    SPANISH("es", "Español", "🇪🇸"),
    GERMAN("de", "Deutsch", "🇩🇪"),
    CHINESE("zh", "中文", "🇨🇳"),
    JAPANESE("ja", "日本語", "🇯🇵"),
    AUTO("auto", "Auto-Detect", "🌐");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
        }
    }
}

data class TranslationStrings(
    // Bottom navigation
    val navCalls: String,
    val navAssistant: String,
    val navAgenda: String,
    val navTasks: String,
    val navSettings: String,

    // Header & Titles
    val appTitle: String,
    val callsTitle: String,
    val callsSubtitle: String,
    val assistantTitle: String,
    val assistantSubtitle: String,
    val agendaTitle: String,
    val agendaSubtitle: String,
    val tasksTitle: String,
    val tasksSubtitle: String,
    val settingsTitle: String,
    val settingsSubtitle: String,

    // Summary & Calls
    val callSummary: String,
    val audioTranscript: String,
    val detectedAppointment: String,
    val validateSummary: String,
    val editSummary: String,
    val confirmAppointment: String,
    val dismissAppointment: String,
    val noSpeechDetected: String,
    val loadingAnalysis: String,
    val retry: String,
    val lowConfidenceWarning: String,
    val lowConfidenceSubtitle: String,
    val incomingCall: String,
    val outgoingCall: String,
    val dialNumber: String,
    val startCall: String,
    val contactsList: String,
    val allCalls: String,
    val historyTab: String,
    val contactsTab: String,
    val aiConsentTitle: String,
    val aiConsentActive: String,
    val aiConsentInactive: String,
    val searchContactPlaceholder: String,

    // Chat
    val chatPlaceholder: String,
    val sendButton: String,
    val chatGreeting: String,
    val chatAnalyzing: String,
    val newChat: String,
    val chatHistory: String,

    // Tasks & Agenda
    val addTask: String,
    val taskTitlePlaceholder: String,
    val noTasks: String,
    val tasksHeader: String,
    val allTasksFilter: String,
    val pendingTasksFilter: String,
    val completedTasksFilter: String,
    val noAppointments: String,
    val addAppointment: String,
    val agendaHeader: String,
    val agendaClockSubtitle: String,

    // Settings
    val profileTab: String,
    val advancedTab: String,
    val languageSection: String,
    val languageSubtitle: String,
    val themeSection: String,
    val themeSubtitle: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,
    val autoRecordCalls: String,
    val hqAudio: String,
    val serverUrl: String,
    val save: String,
    val logout: String,
    val changePassword: String,
    val editProfile: String,
    val gdprVoiceExport: String,
    val gdprAllExport: String,
    val gdprDeleteVoice: String,

    // Additional Call History & Filter Keys
    val callHistoryAll: String,
    val callHistoryMissed: String,
    val callHistoryWithSummary: String,
    val callHistoryEmpty: String,
    val callHistorySynchronized: String,

    // Agenda Keys
    val planAppointment: String,
    val appointmentTitlePlaceholder: String,
    val today: String,
    val tomorrow: String,
    val afterTomorrow: String,
    val oneWeek: String,
    val calendarPicker: String,
    val dayLabel: String,
    val hourLabel: String,

    // Settings & Advanced Settings Keys
    val recordPrefsSection: String,
    val autoRecordDesc: String,
    val hdAudioWav: String,
    val hqAudioDesc: String,
    val aiEnginesSection: String,
    val aiEnginesSubtitle: String,
    val activePipeline: String,
    val saveAiApiKeys: String,
    val cloudTelephonySection: String,
    val cloudTelephonySubtitle: String,
    val shizukuSection: String,
    val serverConfigSection: String,
    val gdprSection: String,
    val exportGdpr: String,
    val deleteVoiceOnly: String,
    val deleteAccount: String,
    val testServer: String,
    val saveServer: String,
    val close: String,
    val validate: String,
    val delete: String,
    val active: String,
    val open: String,
    val noChatRecorded: String,

    // Tasks and Audio Vault Keys
    val audioVault: String,
    val noAudioRecordings: String,
    val playingAudio: String,
    val priorityLabel: String,
    val priorityUrgent: String,
    val priorityImportant: String,
    val priorityNormal: String,
    val detectedByAi: String,
    val shareRecording: String,
    val gdprVoiceConsentDesc: String,

    // Calling and Active Call Keys
    val dialCallTitle: String,
    val selectContactToCall: String,
    val noContactsFound: String,
    val connectingStatus: String,
    val onCallAiActive: String,
    val onCallPlain: String,
    val muteLabel: String,
    val unmuteLabel: String,
    val speakerLabel: String,
    val receiverLabel: String,
    val listeningStatus: String,
    val waitingForSpeech: String,
    val endCallLabel: String,
    val callDisconnected: String,
    val callError: String,

    // Advanced Settings & Inputs
    val aiSettingsDescription: String,
    val groqApiKeyLabel: String,
    val deepgramApiKeyLabel: String,
    val openAiApiKeyLabel: String,
    val sttModelLabel: String,
    val llmModelLabel: String,
    val voipSelectProviderLabel: String,
    val virtualNumberLabel: String,
    val saveVoipCredentials: String,
    val shizukuStatusConnected: String,
    val shizukuStatusRequired: String,
    val shizukuStatusStopped: String,
    val authorizeShizuku: String,
    val serverUrlLabel: String,
    val usbLocalMode: String,
    val wifiNetworkMode: String,
    val gdprNoticeText: String,
    val deleteAccountWarning: String,
    val voiceDictationNotAvailable: String
)

val EnglishStrings = TranslationStrings(
    navCalls = "Calls",
    navAssistant = "AI Assistant",
    navAgenda = "Agenda",
    navTasks = "Tasks",
    navSettings = "Settings",
    appTitle = "Intelligent Calls",
    callsTitle = "Call Intelligence",
    callsSubtitle = "PSTN Call Recording & Live Transcription",
    assistantTitle = "AI Assistant",
    assistantSubtitle = "Real-Time CRM & Telephony Intelligence",
    agendaTitle = "Agenda & Meetings",
    agendaSubtitle = "AI Extracted Calendar Events",
    tasksTitle = "Action Items",
    tasksSubtitle = "Synchronized CRM To-Do List",
    settingsTitle = "Settings",
    settingsSubtitle = "Profile, Language, Theme, VoIP & GDPR",
    callSummary = "Call Summary",
    audioTranscript = "Audio Transcript",
    detectedAppointment = "Detected Appointment",
    validateSummary = "Validate Summary",
    editSummary = "Edit Summary",
    confirmAppointment = "Confirm Meeting",
    dismissAppointment = "Dismiss",
    noSpeechDetected = "No distinct speech detected in this recording.",
    loadingAnalysis = "Loading AI analysis...",
    retry = "Retry",
    lowConfidenceWarning = "Low AI Confidence Score (< 60%)",
    lowConfidenceSubtitle = "Please review and adjust the summary or meeting details.",
    incomingCall = "Incoming Call",
    outgoingCall = "Outgoing Call",
    dialNumber = "Dial a phone number...",
    startCall = "Call",
    contactsList = "Address Book",
    allCalls = "All Calls",
    historyTab = "History",
    contactsTab = "Contacts",
    aiConsentTitle = "AI Transcription & Analysis",
    aiConsentActive = "Active: Calls will be transcribed & summarized",
    aiConsentInactive = "Disabled: Standard audio call",
    searchContactPlaceholder = "Search contacts...",
    chatPlaceholder = "Ask about your calls, tasks, or contacts...",
    sendButton = "Send",
    chatGreeting = "Hello! I am your Intelligent Calls AI assistant. How can I help you today?",
    chatAnalyzing = "AI Assistant is analyzing calls...",
    newChat = "New",
    chatHistory = "History",
    addTask = "Add Task",
    taskTitlePlaceholder = "Task description...",
    noTasks = "No tasks yet. Create one or let AI extract it from calls.",
    tasksHeader = "AI DETECTED TASKS",
    allTasksFilter = "All",
    pendingTasksFilter = "Pending",
    completedTasksFilter = "Completed",
    noAppointments = "No scheduled appointments.",
    addAppointment = "New Event",
    agendaHeader = "CALENDAR & APPOINTMENTS",
    agendaClockSubtitle = "AI Synchronized Agenda",
    profileTab = "Profile & Preferences",
    advancedTab = "Advanced Settings",
    languageSection = "LANGUAGE & AI INTELLIGENCE",
    languageSubtitle = "Whisper STT, AI Summaries & Chatbot",
    themeSection = "THEME & APPEARANCE",
    themeSubtitle = "Customize visual display mode",
    themeDark = "Dark",
    themeLight = "Light",
    themeSystem = "System",
    autoRecordCalls = "Automatic Call Recording",
    hqAudio = "High Quality Audio (AAC HD)",
    serverUrl = "Server Base URL",
    save = "Save",
    logout = "Log Out",
    changePassword = "Password",
    editProfile = "Edit Profile",
    gdprVoiceExport = "Export Voice Data",
    gdprAllExport = "Export All CRM Data",
    gdprDeleteVoice = "Erase Voice Data",
    callHistoryAll = "All",
    callHistoryMissed = "Missed",
    callHistoryWithSummary = "With summary",
    callHistoryEmpty = "No calls in history",
    callHistorySynchronized = "Synchronized",
    planAppointment = "SCHEDULE AN APPOINTMENT",
    appointmentTitlePlaceholder = "Meeting title...",
    today = "Today",
    tomorrow = "Tomorrow",
    afterTomorrow = "Day after tomorrow",
    oneWeek = "+1 wk",
    calendarPicker = "📅 Calendar...",
    dayLabel = "DAY:",
    hourLabel = "TIME:",
    recordPrefsSection = "CALL & RECORDING PREFERENCES",
    autoRecordDesc = "Native call pickup interception",
    hdAudioWav = "HD Audio Format (16kHz WAV)",
    hqAudioDesc = "Optimal accuracy for Whisper & Deepgram",
    aiEnginesSection = "AI ENGINES & API ACCESS KEYS",
    aiEnginesSubtitle = "Groq, Deepgram STT, OpenAI & Whisper",
    activePipeline = "Active Pipeline",
    saveAiApiKeys = "Save AI API Keys",
    cloudTelephonySection = "CLOUD TELEPHONY & MULTI-VOIP",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunk",
    shizukuSection = "SHIZUKU API — ELEVATED ADB PERMISSIONS",
    serverConfigSection = "BACKEND SERVER CONFIGURATION",
    gdprSection = "GDPR & DATA PRIVACY",
    exportGdpr = "Export My Data (GDPR Art. 15)",
    deleteVoiceOnly = "Delete Audio Recordings Only",
    deleteAccount = "Delete Account & All Data",
    testServer = "Test",
    saveServer = "Save",
    close = "Close",
    validate = "Confirm",
    delete = "Delete",
    active = "Active",
    open = "Open",
    noChatRecorded = "No conversations recorded.",
    audioVault = "AUDIO VAULT",
    noAudioRecordings = "No audio recordings yet",
    playingAudio = "Playing audio...",
    priorityLabel = "Priority:",
    priorityUrgent = "URGENT",
    priorityImportant = "IMPORTANT",
    priorityNormal = "NORMAL",
    detectedByAi = "Detected by AI · Intelligent Calls",
    shareRecording = "Share recording",
    gdprVoiceConsentDesc = "Voice Data Consent (AI Training & Analysis)",
    dialCallTitle = "Make a Call",
    selectContactToCall = "Select a contact to start the call:",
    noContactsFound = "No contacts recorded",
    connectingStatus = "Connecting...",
    onCallAiActive = "ON CALL - AI TRANSCRIPTION ACTIVE",
    onCallPlain = "ON CALL (PLAIN VoIP)",
    muteLabel = "Mute",
    unmuteLabel = "Unmute",
    speakerLabel = "Speaker",
    receiverLabel = "Receiver",
    listeningStatus = "Listening...",
    waitingForSpeech = "Waiting for speech...",
    endCallLabel = "End",
    callDisconnected = "Call Disconnected",
    callError = "Call Error",
    aiSettingsDescription = "Configure your personal API keys for high-fidelity speech transcription and automated summaries:",
    groqApiKeyLabel = "Groq API Key (gsk_...)",
    deepgramApiKeyLabel = "Deepgram API Key (Nova-2 Speech-to-Text)",
    openAiApiKeyLabel = "OpenAI / Claude / Gemini API Key",
    sttModelLabel = "Speech-to-Text Model (STT):",
    llmModelLabel = "LLM Engine for Summary & Agenda:",
    voipSelectProviderLabel = "Select your Cloud VoIP provider for 2-Way HD recording and automatic transcription:",
    virtualNumberLabel = "Virtual Number / Gateway (+33...)",
    saveVoipCredentials = "Save VoIP Credentials",
    shizukuStatusConnected = "Shizuku Connected (ADB Permissions Active)",
    shizukuStatusRequired = "Shizuku Detected (Permission required)",
    shizukuStatusStopped = "Shizuku Not Detected / Service stopped",
    authorizeShizuku = "Authorize Shizuku",
    serverUrlLabel = "Server URL (e.g. http://127.0.0.1:8000)",
    usbLocalMode = "USB Local",
    wifiNetworkMode = "Wi-Fi Network",
    gdprNoticeText = "In compliance with GDPR regulations, you have the right to access, export, and permanently delete your data.",
    deleteAccountWarning = "In accordance with Art. 17 of GDPR (Right to Erasure), your account, contacts, calls, recordings, and summaries will be permanently erased. This action cannot be undone.",
    voiceDictationNotAvailable = "Voice dictation is not available on this device"
)

val FrenchStrings = TranslationStrings(
    navCalls = "Appels",
    navAssistant = "Assistant IA",
    navAgenda = "Agenda",
    navTasks = "Tâches",
    navSettings = "Paramètres",
    appTitle = "Intelligent Calls",
    callsTitle = "Intelligence d'Appel",
    callsSubtitle = "Enregistrement PSTN & Transcription en direct",
    assistantTitle = "Assistant IA",
    assistantSubtitle = "Intelligence CRM & Téléphonie en direct",
    agendaTitle = "Agenda & Rendez-vous",
    agendaSubtitle = "Événements extraits par l'IA",
    tasksTitle = "Plan d'Action",
    tasksSubtitle = "Liste des tâches CRM synchronisées",
    settingsTitle = "Paramètres",
    settingsSubtitle = "Profil, Langue, Thème, VoIP & RGPD",
    callSummary = "Résumé de l'appel",
    audioTranscript = "Transcription audio",
    detectedAppointment = "Rendez-vous détecté",
    validateSummary = "Valider le résumé",
    editSummary = "Modifier le résumé",
    confirmAppointment = "Confirmer le RDV",
    dismissAppointment = "Ignorer",
    noSpeechDetected = "Aucune parole distincte détectée dans cet enregistrement.",
    loadingAnalysis = "Chargement de l'analyse...",
    retry = "Réessayer",
    lowConfidenceWarning = "Score de confiance IA faible (< 60%)",
    lowConfidenceSubtitle = "Veuillez vérifier et ajuster le résumé ou les informations du rendez-vous.",
    incomingCall = "Appel Entrant",
    outgoingCall = "Appel Sortant",
    dialNumber = "Composer un numéro...",
    startCall = "Appeler",
    contactsList = "Répertoire",
    allCalls = "Tous les appels",
    historyTab = "Historique",
    contactsTab = "Contacts",
    aiConsentTitle = "Transcription & Analyse IA",
    aiConsentActive = "Actif: Les appels seront transcrits & résumés",
    aiConsentInactive = "Désactivé: Appel audio classique",
    searchContactPlaceholder = "Rechercher un contact...",
    chatPlaceholder = "Posez une question sur vos appels, tâches ou contacts...",
    sendButton = "Envoyer",
    chatGreeting = "Bonjour ! Je suis votre assistant Intelligent Calls. Comment puis-je vous aider ?",
    chatAnalyzing = "L'assistant analyse vos appels...",
    newChat = "Nouveau",
    chatHistory = "Historique",
    addTask = "Ajouter une tâche",
    taskTitlePlaceholder = "Description de la tâche...",
    noTasks = "Aucune tâche pour le moment.",
    tasksHeader = "TÂCHES DÉTECTÉES PAR L'IA",
    allTasksFilter = "Toutes",
    pendingTasksFilter = "En cours",
    completedTasksFilter = "Terminées",
    noAppointments = "Aucun rendez-vous planifié.",
    addAppointment = "Nouvel événement",
    agendaHeader = "AGENDA & RENDEZ-VOUS",
    agendaClockSubtitle = "Agenda synchronisé par IA",
    profileTab = "Profil & Préférences",
    advancedTab = "Paramètres Avancés",
    languageSection = "LANGUE & INTELLIGENCE IA",
    languageSubtitle = "Transcription Whisper, Résumés & Assistant",
    themeSection = "APPARENCE & THÈME",
    themeSubtitle = "Personnalisez le mode d'affichage",
    themeDark = "Sombre",
    themeLight = "Clair",
    themeSystem = "Système",
    autoRecordCalls = "Enregistrement automatique des appels",
    hqAudio = "Audio Haute Définition (AAC HD)",
    serverUrl = "Adresse du serveur",
    save = "Enregistrer",
    logout = "Se déconnecter",
    changePassword = "Mot de passe",
    editProfile = "Modifier Profil",
    gdprVoiceExport = "Exporter Données Vocales",
    gdprAllExport = "Export Complet RGPD",
    gdprDeleteVoice = "Purger Données Vocales",
    callHistoryAll = "Tous",
    callHistoryMissed = "Manqués",
    callHistoryWithSummary = "Avec résumé",
    callHistoryEmpty = "Aucun appel dans l'historique",
    callHistorySynchronized = "Synchronisé",
    planAppointment = "PLANIFIER UN RENDEZ-VOUS",
    appointmentTitlePlaceholder = "Titre du RDV...",
    today = "Aujourd'hui",
    tomorrow = "Demain",
    afterTomorrow = "Après-demain",
    oneWeek = "+1 sem",
    calendarPicker = "📅 Calendrier...",
    dayLabel = "JOUR :",
    hourLabel = "HEURE :",
    recordPrefsSection = "PRÉFÉRENCES D'ENREGISTREMENT & APPELS",
    autoRecordDesc = "Interception native lors du décrochage",
    hdAudioWav = "Format Audio HD (16kHz WAV)",
    hqAudioDesc = "Précision optimale pour Whisper & Deepgram",
    aiEnginesSection = "MOTEURS IA & CLÉS D'ACCÈS API",
    aiEnginesSubtitle = "Groq, Deepgram STT, OpenAI & Whisper",
    activePipeline = "Pipeline Actif",
    saveAiApiKeys = "Enregistrer les Clés API IA",
    cloudTelephonySection = "CLOUD TELEPHONY & MULTI-VOIP",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunk",
    shizukuSection = "SHIZUKU API — PERMISSIONS ÉLEVÉES ADB",
    serverConfigSection = "CONFIGURATION SERVEUR BACKEND",
    gdprSection = "RGPD & PROTECTION DES DONNÉES",
    exportGdpr = "Exporter mes données (Art. 15 RGPD)",
    deleteVoiceOnly = "Effacer uniquement les enregistrements",
    deleteAccount = "Supprimer mon compte & mes données",
    testServer = "Tester",
    saveServer = "Enregistrer",
    close = "Fermer",
    validate = "Valider",
    delete = "Supprimer",
    active = "Actif",
    open = "Ouvrir",
    noChatRecorded = "Aucune conversation enregistrée.",
    audioVault = "COFFRE-FORT AUDIO",
    noAudioRecordings = "Aucun enregistrement audio pour le moment",
    playingAudio = "En cours de lecture...",
    priorityLabel = "Priorité :",
    priorityUrgent = "URGENT",
    priorityImportant = "IMPORTANT",
    priorityNormal = "NORMAL",
    detectedByAi = "Détecté par IA · Intelligent Calls",
    shareRecording = "Partager l'enregistrement",
    gdprVoiceConsentDesc = "Consentement données vocales",
    dialCallTitle = "Composer un appel",
    selectContactToCall = "Sélectionnez un contact pour lancer l'appel :",
    noContactsFound = "Aucun contact enregistré",
    connectingStatus = "Connexion en cours...",
    onCallAiActive = "EN APPEL - TRANSCRIPTION IA ACTIVE",
    onCallPlain = "EN APPEL (VoIP STANDARD)",
    muteLabel = "Muet",
    unmuteLabel = "Micro",
    speakerLabel = "Haut-parleur",
    receiverLabel = "Écouteur",
    listeningStatus = "Écoute active...",
    waitingForSpeech = "En attente de voix...",
    endCallLabel = "Fin",
    callDisconnected = "Appel terminé",
    callError = "Erreur d'appel",
    aiSettingsDescription = "Renseignez vos clés d'API personnelles pour activer la transcription vocale haute fidélité et les résumés automatiques :",
    groqApiKeyLabel = "Clé API Groq (gsk_...)",
    deepgramApiKeyLabel = "Clé API Deepgram (Nova-2 Speech-to-Text)",
    openAiApiKeyLabel = "Clé API OpenAI / Claude / Gemini",
    sttModelLabel = "Modèle Transcription Vocale (STT) :",
    llmModelLabel = "Moteur LLM Synthèse & RDV :",
    voipSelectProviderLabel = "Sélectionnez votre opérateur VoIP Cloud pour l'enregistrement 2-Way HD et la transcription automatique :",
    virtualNumberLabel = "Numéro Virtuel / Passerelle (+33...)",
    saveVoipCredentials = "Enregistrer les identifiants",
    shizukuStatusConnected = "Shizuku Connecté (Permissions ADB Actives)",
    shizukuStatusRequired = "Shizuku Détecté (Permission requise)",
    shizukuStatusStopped = "Shizuku Non Détecté / Service arrêté",
    authorizeShizuku = "Autoriser Shizuku",
    serverUrlLabel = "URL du serveur (ex: http://127.0.0.1:8000)",
    usbLocalMode = "USB Local",
    wifiNetworkMode = "Wi-Fi Réseau",
    gdprNoticeText = "Conformément au RGPD (Règlement Général sur la Protection des Données), vous disposez d'un droit d'accès, d'export et d'effacement complet de vos données.",
    deleteAccountWarning = "Conformément à l'Art. 17 du RGPD (Droit à l'oubli), votre compte, tous vos contacts, appels, enregistrements et résumés seront définitivement effacés. Cette action est irréversible.",
    voiceDictationNotAvailable = "Dictée vocale non disponible sur ce terminal"
)

val ArabicStrings = TranslationStrings(
    navCalls = "المكالمات",
    navAssistant = "المساعد الذكي",
    navAgenda = "المواعيد",
    navTasks = "المهام",
    navSettings = "الإعدادات",
    appTitle = "Intelligent Calls",
    callsTitle = "ذكاء المكالمات",
    callsSubtitle = "تسجيل المكالمات والتفريغ الصوتي الفوري",
    assistantTitle = "المساعد الذكي",
    assistantSubtitle = "معلومات فورية حول المهام والمكالمات",
    agendaTitle = "جدول المواعيد",
    agendaSubtitle = "المواعيد المستخرجة بواسطة الذكاء الاصطناعي",
    tasksTitle = "قائمة المهام",
    tasksSubtitle = "المهام والإجراءات المتزامنة",
    settingsTitle = "الإعدادات",
    settingsSubtitle = "الملف الشخصي، اللغة، المظهر، وخصوصية البيانات",
    callSummary = "ملخص المكالمة",
    audioTranscript = "تفريغ المكالمة الصوتي",
    detectedAppointment = "موعد تم اكتشافه",
    validateSummary = "اعتماد الملخص",
    editSummary = "تعديل الملخص",
    confirmAppointment = "تأكيد الموعد",
    dismissAppointment = "تجاهل",
    noSpeechDetected = "لم يتم رصد أي صوت واضح في هذا التسجيل.",
    loadingAnalysis = "جاري تحليل المكالمة...",
    retry = "إعادة المحاولة",
    lowConfidenceWarning = "درجة دقة الذكاء الاصطناعي منخفضة (< 60%)",
    lowConfidenceSubtitle = "يرجى مراجعة وتعديل ملخص المكالمة أو تفاصيل الموعد.",
    incomingCall = "مكالمة واردة",
    outgoingCall = "مكالمة صادرة",
    dialNumber = "أدخل رقم الهاتف...",
    startCall = "اتصال",
    contactsList = "سجل جهات الاتصال",
    allCalls = "جميع المكالمات",
    historyTab = "السجل",
    contactsTab = "جهات الاتصال",
    aiConsentTitle = "تفريغ وتحليل الذكاء الاصطناعي",
    aiConsentActive = "مفعل: سيتم تفريغ وتلخيص المكالمات تلقائياً",
    aiConsentInactive = "معطل: مكالمة صوتية عادية",
    searchContactPlaceholder = "بحث عن جهة اتصال...",
    chatPlaceholder = "اطرح سؤالاً عن مكالماتك، مواعيدك أو مهامك...",
    sendButton = "إرسال",
    chatGreeting = "مرحباً! أنا مساعدك الذكي لمكالمات العمل. كيف يمكنني مساعدتك اليوم؟",
    chatAnalyzing = "جاري تحليل المكالمات والبيانات...",
    newChat = "محادثة جديدة",
    chatHistory = "سجل المحادثات",
    addTask = "إضافة مهمة",
    taskTitlePlaceholder = "تفاصيل المهمة...",
    noTasks = "لا توجد مهام حالياً.",
    tasksHeader = "المهام المكتشفة بالذكاء الاصطناعي",
    allTasksFilter = "الكل",
    pendingTasksFilter = "قيد التنفيذ",
    completedTasksFilter = "المكتملة",
    noAppointments = "لا توجد مواعيد مسجلة.",
    addAppointment = "موعد جديد",
    agendaHeader = "جدول المواعيد والتقويم",
    agendaClockSubtitle = "مواعيد متزامنة بواسطة الذكاء الاصطناعي",
    profileTab = "الملف الشخصي والتفضيلات",
    advancedTab = "إعدادات متقدمة",
    languageSection = "اللغة والذكاء الاصطناعي",
    languageSubtitle = "تفريغ الصوت، تلخيص المكالمات والمساعد الذكي",
    themeSection = "المظهر والتصميم",
    themeSubtitle = "تخصيص وضع العرض المرئي",
    themeDark = "داكن",
    themeLight = "فاتح",
    themeSystem = "تلقائي",
    autoRecordCalls = "تسجيل المكالمات تلقائياً",
    hqAudio = "صوت عالي الدقة (AAC HD)",
    serverUrl = "عنوان الخادم",
    save = "حفظ",
    logout = "تسجيل الخروج",
    changePassword = "كلمة المرور",
    editProfile = "تعديل الملف",
    gdprVoiceExport = "تصدير التسجيلات الصوتية",
    gdprAllExport = "تصدير كافة البيانات (GDPR)",
    gdprDeleteVoice = "حذف التسجيلات نهائياً",
    callHistoryAll = "الكل",
    callHistoryMissed = "الفائتة",
    callHistoryWithSummary = "مع الملخص",
    callHistoryEmpty = "لا توجد مكالمات في السجل",
    callHistorySynchronized = "متزامن",
    planAppointment = "جدولة موعد",
    appointmentTitlePlaceholder = "عنوان الموعد...",
    today = "اليوم",
    tomorrow = "غداً",
    afterTomorrow = "بعد غد",
    oneWeek = "+1 أسبوع",
    calendarPicker = "📅 التقويم...",
    dayLabel = "اليوم:",
    hourLabel = "الوقت:",
    recordPrefsSection = "تفضيلات التسجيل والمكالمات",
    autoRecordDesc = "اعتراض المكالمات الأصلي عند الرد",
    hdAudioWav = "تنسيق صوتي عالي الدقة (16kHz WAV)",
    hqAudioDesc = "دقة مثالية لنماذج ويسبر وديبجرام",
    aiEnginesSection = "محركات الذكاء الاصطناعي ومفاتيح API",
    aiEnginesSubtitle = "Groq, Deepgram STT, OpenAI & Whisper",
    activePipeline = "المسار النشط",
    saveAiApiKeys = "حفظ مفاتيح API",
    cloudTelephonySection = "هواتف السحابة و VoIP",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunk",
    shizukuSection = "واجهة برمجة تطبيقات شيزوكو - أذونات ADB",
    serverConfigSection = "تكوين خادم الواجهة الخلفية",
    gdprSection = "حماية البيانات والخصوصية",
    exportGdpr = "تصدير بياناتي (المادة 15)",
    deleteVoiceOnly = "مسح التسجيلات الصوتية فقط",
    deleteAccount = "حذف حسابي وجميع البيانات",
    testServer = "اختبار",
    saveServer = "حفظ",
    close = "إغلاق",
    validate = "تأكيد",
    delete = "حذف",
    active = "نشط",
    open = "فتح",
    noChatRecorded = "لا توجد محادثات مسجلة.",
    audioVault = "خزنة الصوت",
    noAudioRecordings = "لا توجد تسجيلات صوتية حتى الآن",
    playingAudio = "جاري تشغيل الصوت...",
    priorityLabel = "الأولوية:",
    priorityUrgent = "عاجل",
    priorityImportant = "هام",
    priorityNormal = "عادي",
    detectedByAi = "مكتشف بواسطة الذكاء الاصطناعي",
    shareRecording = "مشاركة التسجيل",
    gdprVoiceConsentDesc = "الموافقة على معالجة البيانات الصوتية",
    dialCallTitle = "إجراء مكالمة",
    selectContactToCall = "اختر جهة اتصال لبدء المكالمة:",
    noContactsFound = "لم يتم العثور على جهات اتصال",
    connectingStatus = "جاري الاتصال...",
    onCallAiActive = "المكالمة جارية - التفريغ الصوتي مفعل",
    onCallPlain = "المكالمة جارية (صوت عادي)",
    muteLabel = "كتم",
    unmuteLabel = "إلغاء الكتم",
    speakerLabel = "مكبر الصوت",
    receiverLabel = "سماعة الهاتف",
    listeningStatus = "استماع نشط...",
    waitingForSpeech = "في انتظار الحديث...",
    endCallLabel = "إنهاء",
    callDisconnected = "انتهت المكالمة",
    callError = "خطأ في المكالمة",
    aiSettingsDescription = "قم بتكوين مفاتيح API الخاصة بك لتفعيل التحليل والتفريغ الصوتي عالي الدقة:",
    groqApiKeyLabel = "مفتاح API لـ Groq",
    deepgramApiKeyLabel = "مفتاح API لـ Deepgram (STT)",
    openAiApiKeyLabel = "مفتاح API لـ OpenAI / Claude",
    sttModelLabel = "نموذج تحويل الصوت إلى نص (STT):",
    llmModelLabel = "محرك LLM للملخص والمواعيد:",
    voipSelectProviderLabel = "اختر مزود خدمة VoIP السحابي للتسجيل بجودة عالية:",
    virtualNumberLabel = "الرقم الافتراضي (+33...)",
    saveVoipCredentials = "حفظ بيانات VoIP",
    shizukuStatusConnected = "شيزوكو متصل (أذونات ADB نشطة)",
    shizukuStatusRequired = "تم اكتشاف شيزوكو (يتطلب إذن)",
    shizukuStatusStopped = "لم يتم اكتشاف شيزوكو / الخدمة متوقفة",
    authorizeShizuku = "منح الإذن لشيزوكو",
    serverUrlLabel = "عنوان URL للخادم (مثال: http://127.0.0.1:8000)",
    usbLocalMode = "USB محلي",
    wifiNetworkMode = "شبكة Wi-Fi",
    gdprNoticeText = "وفقاً للائحة العامة لحماية البيانات، يحق لك الوصول إلى بياناتك وتصديرها وحذفها نهائياً.",
    deleteAccountWarning = "وفقاً للمادة 17 من اللائحة العامة لحماية البيانات، سيتم حذف حسابك وجميع المكالمات والتسجيلات بشكل نهائي.",
    voiceDictationNotAvailable = "الإملاء الصوتي غير مدعوم على هذا الجهاز"
)

val SpanishStrings = TranslationStrings(
    navCalls = "Llamadas",
    navAssistant = "Asistente IA",
    navAgenda = "Agenda",
    navTasks = "Tareas",
    navSettings = "Ajustes",
    appTitle = "Intelligent Calls",
    callsTitle = "Inteligencia de Llamadas",
    callsSubtitle = "Grabación de llamadas y transcripción en vivo",
    assistantTitle = "Asistente IA",
    assistantSubtitle = "Inteligencia telefónica y CRM en tiempo real",
    agendaTitle = "Agenda y Citas",
    agendaSubtitle = "Eventos extraídos por IA",
    tasksTitle = "Tareas",
    tasksSubtitle = "Lista de tareas sincronizadas",
    settingsTitle = "Ajustes",
    settingsSubtitle = "Perfil, Idioma, Tema, VoIP y RGPD",
    callSummary = "Resumen de la llamada",
    audioTranscript = "Transcripción de audio",
    detectedAppointment = "Cita detectada",
    validateSummary = "Validar resumen",
    editSummary = "Editar resumen",
    confirmAppointment = "Confirmar Cita",
    dismissAppointment = "Descartar",
    noSpeechDetected = "No se detectó voz clara en esta grabación.",
    loadingAnalysis = "Cargando análisis de IA...",
    retry = "Reintentar",
    lowConfidenceWarning = "Puntuación de confianza de IA baja (< 60%)",
    lowConfidenceSubtitle = "Por favor, revise y ajuste el resumen o los detalles de la reunión.",
    incomingCall = "Llamada Entrante",
    outgoingCall = "Llamada Saliente",
    dialNumber = "Marcar un número...",
    startCall = "Llamar",
    contactsList = "Contactos",
    allCalls = "Todas las llamadas",
    historyTab = "Historial",
    contactsTab = "Contactos",
    aiConsentTitle = "Transcripción y Análisis IA",
    aiConsentActive = "Activo: Las llamadas se transcribirán y resumirán",
    aiConsentInactive = "Desactivado: Llamada estándar",
    searchContactPlaceholder = "Buscar contacto...",
    chatPlaceholder = "Pregunta sobre llamadas, tareas o contactos...",
    sendButton = "Enviar",
    chatGreeting = "¡Hola! Soy tu asistente de llamadas inteligente. ¿En qué puedo ayudarte?",
    chatAnalyzing = "El asistente está analizando tus llamadas...",
    newChat = "Nueva",
    chatHistory = "Historial",
    addTask = "Añadir Tarea",
    taskTitlePlaceholder = "Descripción de la tarea...",
    noTasks = "No hay tareas pendientes.",
    tasksHeader = "TAREAS DETECTADAS POR IA",
    allTasksFilter = "Todas",
    pendingTasksFilter = "Pendientes",
    completedTasksFilter = "Completadas",
    noAppointments = "No hay citas programadas.",
    addAppointment = "Nueva Cita",
    agendaHeader = "AGENDA Y CITAS",
    agendaClockSubtitle = "Agenda sincronizada por IA",
    profileTab = "Perfil y Preferencias",
    advancedTab = "Ajustes Avanzados",
    languageSection = "IDIOMA E INTELIGENCIA IA",
    languageSubtitle = "Transcripción Whisper, Resúmenes y Asistente",
    themeSection = "TEMA Y APARIENCIA",
    themeSubtitle = "Personaliza el modo visual",
    themeDark = "Oscuro",
    themeLight = "Claro",
    themeSystem = "Sistema",
    autoRecordCalls = "Grabación automática de llamadas",
    hqAudio = "Audio de alta definición (AAC HD)",
    serverUrl = "URL del servidor",
    save = "Guardar",
    logout = "Cerrar sesión",
    changePassword = "Contraseña",
    editProfile = "Editar Perfil",
    gdprVoiceExport = "Exportar Datos de Voz",
    gdprAllExport = "Exportar Datos RGPD",
    gdprDeleteVoice = "Borrar Datos de Voz",
    callHistoryAll = "Todas",
    callHistoryMissed = "Perdidas",
    callHistoryWithSummary = "Con resumen",
    callHistoryEmpty = "No hay llamadas en el historial",
    callHistorySynchronized = "Sincronizado",
    planAppointment = "PROGRAMAR UNA CITA",
    appointmentTitlePlaceholder = "Título de la cita...",
    today = "Hoy",
    tomorrow = "Mañana",
    afterTomorrow = "Pasado mañana",
    oneWeek = "+1 sem",
    calendarPicker = "📅 Calendario...",
    dayLabel = "DÍA:",
    hourLabel = "HORA:",
    recordPrefsSection = "PREFERENCIAS DE LLAMADA Y GRABACIÓN",
    autoRecordDesc = "Intercepción nativa al descolgar",
    hdAudioWav = "Formato de audio HD (16kHz WAV)",
    hqAudioDesc = "Precisión óptima para Whisper y Deepgram",
    aiEnginesSection = "MOTORES DE IA Y CLAVES API",
    aiEnginesSubtitle = "Groq, Deepgram STT, OpenAI & Whisper",
    activePipeline = "Canal activo",
    saveAiApiKeys = "Guardar Claves API IA",
    cloudTelephonySection = "CLOUD TELEPHONY Y MULTI-VOIP",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunk",
    shizukuSection = "API SHIZUKU — PERMISOS ELEVADOS ADB",
    serverConfigSection = "CONFIGURACIÓN DEL SERVIDOR",
    gdprSection = "RGPD Y PROTECCIÓN DE DATOS",
    exportGdpr = "Exportar mis datos (Art. 15 RGPD)",
    deleteVoiceOnly = "Borrar solo grabaciones de voz",
    deleteAccount = "Eliminar mi cuenta y datos",
    testServer = "Probar",
    saveServer = "Guardar",
    close = "Cerrar",
    validate = "Validar",
    delete = "Eliminar",
    active = "Activo",
    open = "Abrir",
    noChatRecorded = "No hay conversaciones guardadas.",
    audioVault = "BAÚL DE AUDIO",
    noAudioRecordings = "No hay grabaciones de audio aún",
    playingAudio = "Reproduciendo audio...",
    priorityLabel = "Prioridad:",
    priorityUrgent = "URGENTE",
    priorityImportant = "IMPORTANTE",
    priorityNormal = "NORMAL",
    detectedByAi = "Detectado por IA · Intelligent Calls",
    shareRecording = "Compartir grabación",
    gdprVoiceConsentDesc = "Consentimiento de datos de voz",
    dialCallTitle = "Realizar una llamada",
    selectContactToCall = "Seleccione un contacto para llamar:",
    noContactsFound = "No hay contactos registrados",
    connectingStatus = "Conectando...",
    onCallAiActive = "EN LLAMADA - TRANSCRIPCIÓN IA ACTIVA",
    onCallPlain = "EN LLAMADA (VoIP ESTÁNDAR)",
    muteLabel = "Silenciar",
    unmuteLabel = "Activar micro",
    speakerLabel = "Altavoz",
    receiverLabel = "Auricular",
    listeningStatus = "Escuchando...",
    waitingForSpeech = "Esperando voz...",
    endCallLabel = "Colgar",
    callDisconnected = "Llamada finalizada",
    callError = "Error en la llamada",
    aiSettingsDescription = "Configure sus claves de API para la transcripción y los resúmenes automáticos:",
    groqApiKeyLabel = "Clave API de Groq",
    deepgramApiKeyLabel = "Clave API de Deepgram (STT)",
    openAiApiKeyLabel = "Clave API de OpenAI / Claude",
    sttModelLabel = "Modelo de transcripción de voz (STT):",
    llmModelLabel = "Motor LLM para resúmenes y citas:",
    voipSelectProviderLabel = "Seleccione su proveedor VoIP Cloud para grabación 2-Way HD:",
    virtualNumberLabel = "Número virtual (+33...)",
    saveVoipCredentials = "Guardar credenciales",
    shizukuStatusConnected = "Shizuku Conectado (Permisos ADB activos)",
    shizukuStatusRequired = "Shizuku Detectado (Permiso requerido)",
    shizukuStatusStopped = "Shizuku No Detectado / Servicio detenido",
    authorizeShizuku = "Autorizar Shizuku",
    serverUrlLabel = "URL del servidor (ej: http://127.0.0.1:8000)",
    usbLocalMode = "USB Local",
    wifiNetworkMode = "Red Wi-Fi",
    gdprNoticeText = "De conformidad con el RGPD, tiene derecho a acceder, exportar y borrar sus datos.",
    deleteAccountWarning = "Conforme al Art. 17 del RGPD, su cuenta y todos los datos serán eliminados permanentemente.",
    voiceDictationNotAvailable = "Dictado de voz no disponible en este dispositivo"
)

val GermanStrings = TranslationStrings(
    navCalls = "Anrufe",
    navAssistant = "KI-Assistent",
    navAgenda = "Termine",
    navTasks = "Aufgaben",
    navSettings = "Einstellungen",
    appTitle = "Intelligent Calls",
    callsTitle = "Anruf-Intelligenz",
    callsSubtitle = "Anrufaufzeichnung & Live-Transkription",
    assistantTitle = "KI-Assistent",
    assistantSubtitle = "Echtzeit-Telefonauskunft & CRM",
    agendaTitle = "Termine & Kalender",
    agendaSubtitle = "Von KI erkannte Termine",
    tasksTitle = "Aufgabenliste",
    tasksSubtitle = "Synchronisierte Aufgaben",
    settingsTitle = "Einstellungen",
    settingsSubtitle = "Profil, Sprache, Design, VoIP & DSGVO",
    callSummary = "Anrufzusammenfassung",
    audioTranscript = "Audiotranskription",
    detectedAppointment = "Erkannter Termin",
    validateSummary = "Zusammenfassung bestätigen",
    editSummary = "Bearbeiten",
    confirmAppointment = "Termin bestätigen",
    dismissAppointment = "Verwerfen",
    noSpeechDetected = "In dieser Aufnahme wurde keine deutliche Sprache erkannt.",
    loadingAnalysis = "KI-Analyse wird geladen...",
    retry = "Wiederholen",
    lowConfidenceWarning = "Niedriger KI-Konfidenzwert (< 60%)",
    lowConfidenceSubtitle = "Bitte überprüfen und bearbeiten Sie die Zusammenfassung oder Termindetails.",
    incomingCall = "Eingehender Anruf",
    outgoingCall = "Ausgehender Anruf",
    dialNumber = "Telefonnummer wählen...",
    startCall = "Anrufen",
    contactsList = "Kontakte",
    allCalls = "Alle Anrufe",
    historyTab = "Verlauf",
    contactsTab = "Kontakte",
    aiConsentTitle = "KI-Transkription & Analyse",
    aiConsentActive = "Aktiv: Anrufe werden transkribiert & zusammengefasst",
    aiConsentInactive = "Deaktiviert: Normaler Anruf",
    searchContactPlaceholder = "Kontakt suchen...",
    chatPlaceholder = "Fragen Sie nach Anrufen, Aufgaben oder Kontakten...",
    sendButton = "Senden",
    chatGreeting = "Hallo! Ich bin Ihr intelligenter Anruf-Assistent. Wie kann ich helfen?",
    chatAnalyzing = "Der Assistent analysiert Anrufe...",
    newChat = "Neu",
    chatHistory = "Verlauf",
    addTask = "Aufgabe hinzufügen",
    taskTitlePlaceholder = "Aufgabenbeschreibung...",
    noTasks = "Keine Aufgaben vorhanden.",
    tasksHeader = "VON KI ERKANNTE AUFGABEN",
    allTasksFilter = "Alle",
    pendingTasksFilter = "Offen",
    completedTasksFilter = "Erledigt",
    noAppointments = "Keine Termine geplant.",
    addAppointment = "Neuer Termin",
    agendaHeader = "TERMINE & KALENDER",
    agendaClockSubtitle = "KI-synchronisierter Terminkalender",
    profileTab = "Profil & Einstellungen",
    advancedTab = "Erweiterte Optionen",
    languageSection = "SPRACHE & KI-INTELLIGENZ",
    languageSubtitle = "Whisper-Transkription, KI-Zusammenfassung & Chatbot",
    themeSection = "DESIGN & ERSCHEINUNGSBILD",
    themeSubtitle = "Anzeigemodus anpassen",
    themeDark = "Dunkel",
    themeLight = "Hell",
    themeSystem = "System",
    autoRecordCalls = "Automatische Anrufaufnahme",
    hqAudio = "Hochwertiges Audio (AAC HD)",
    serverUrl = "Server-URL",
    save = "Speichern",
    logout = "Abmelden",
    changePassword = "Passwort",
    editProfile = "Profil bearbeiten",
    gdprVoiceExport = "Sprachdaten exportieren",
    gdprAllExport = "Alle DSGVO-Daten exportieren",
    gdprDeleteVoice = "Sprachdaten löschen",
    callHistoryAll = "Alle",
    callHistoryMissed = "Verpasst",
    callHistoryWithSummary = "Mit Zusammenfassung",
    callHistoryEmpty = "Keine Anrufe im Verlauf",
    callHistorySynchronized = "Synchronisiert",
    planAppointment = "TERMIN PLANEN",
    appointmentTitlePlaceholder = "Termintitel...",
    today = "Heute",
    tomorrow = "Morgen",
    afterTomorrow = "Übermorgen",
    oneWeek = "+1 Woche",
    calendarPicker = "📅 Kalender...",
    dayLabel = "TAG:",
    hourLabel = "UHRZEIT:",
    recordPrefsSection = "AUFNAHME- & ANRUFEINSTELLUNGEN",
    autoRecordDesc = "Natives Abfangen bei Gesprächsannahme",
    hdAudioWav = "HD-Audioformat (16kHz WAV)",
    hqAudioDesc = "Optimale Genauigkeit für Whisper & Deepgram",
    aiEnginesSection = "KI-ENGINES & API-SCHLÜSSEL",
    aiEnginesSubtitle = "Groq, Deepgram STT, OpenAI & Whisper",
    activePipeline = "Aktive Pipeline",
    saveAiApiKeys = "KI-API-Schlüssel speichern",
    cloudTelephonySection = "CLOUD-TELEFONIE & MULTI-VOIP",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunk",
    shizukuSection = "SHIZUKU API — ERWEITERTE ADB-RECHTE",
    serverConfigSection = "BACKEND-SERVER-KONFIGURATION",
    gdprSection = "DSGVO & DATENSCHUTZ",
    exportGdpr = "Meine Daten exportieren (Art. 15 DSGVO)",
    deleteVoiceOnly = "Nur Sprachaufnahmen löschen",
    deleteAccount = "Konto & alle Daten löschen",
    testServer = "Testen",
    saveServer = "Speichern",
    close = "Schließen",
    validate = "Bestätigen",
    delete = "Löschen",
    active = "Aktiv",
    open = "Öffnen",
    noChatRecorded = "Keine Unterhaltungen aufgezeichnet.",
    audioVault = "AUDIO-TRESOR",
    noAudioRecordings = "Noch keine Audioaufnahmen vorhanden",
    playingAudio = "Wiedergabe läuft...",
    priorityLabel = "Priorität:",
    priorityUrgent = "DRINGEND",
    priorityImportant = "WICHTIG",
    priorityNormal = "NORMAL",
    detectedByAi = "Von KI erkannt · Intelligent Calls",
    shareRecording = "Aufnahme teilen",
    gdprVoiceConsentDesc = "Einwilligung zur Sprachdatenverarbeitung",
    dialCallTitle = "Anruf tätigen",
    selectContactToCall = "Wählen Sie einen Kontakt für den Anruf:",
    noContactsFound = "Keine Kontakte gefunden",
    connectingStatus = "Verbindung wird hergestellt...",
    onCallAiActive = "IM GESPRÄCH - KI-TRANSKRIPTION AKTIV",
    onCallPlain = "IM GESPRÄCH (STANDARD-VoIP)",
    muteLabel = "Stummschalten",
    unmuteLabel = "Stummschaltung aufheben",
    speakerLabel = "Lautsprecher",
    receiverLabel = "Hörer",
    listeningStatus = "Hört zu...",
    waitingForSpeech = "Warte auf Sprache...",
    endCallLabel = "Auflegen",
    callDisconnected = "Anruf beendet",
    callError = "Anruffehler",
    aiSettingsDescription = "Konfigurieren Sie Ihre API-Schlüssel für präzise Sprachtranskription und Zusammenfassungen:",
    groqApiKeyLabel = "Groq API-Schlüssel",
    deepgramApiKeyLabel = "Deepgram API-Schlüssel (STT)",
    openAiApiKeyLabel = "OpenAI / Claude API-Schlüssel",
    sttModelLabel = "Sprach-zu-Text-Modell (STT):",
    llmModelLabel = "LLM-Engine für Zusammenfassungen & Termine:",
    voipSelectProviderLabel = "Wählen Sie Ihren Cloud-VoIP-Anbieter für HD-Aufnahmen:",
    virtualNumberLabel = "Virtuelle Nummer (+33...)",
    saveVoipCredentials = "Anmeldedaten speichern",
    shizukuStatusConnected = "Shizuku Verbunden (ADB-Rechte aktiv)",
    shizukuStatusRequired = "Shizuku Erkannt (Berechtigung erforderlich)",
    shizukuStatusStopped = "Shizuku Nicht Erkannt / Dienst gestoppt",
    authorizeShizuku = "Shizuku Autorisieren",
    serverUrlLabel = "Server-URL (z.B. http://127.0.0.1:8000)",
    usbLocalMode = "USB Lokal",
    wifiNetworkMode = "WLAN-Netzwerk",
    gdprNoticeText = "Gemäß DSGVO haben Sie das Recht auf Zugriff, Export und Löschung Ihrer Daten.",
    deleteAccountWarning = "Gemäß Art. 17 DSGVO werden Ihr Konto und alle zugehörigen Daten unwiderruflich gelöscht.",
    voiceDictationNotAvailable = "Sprachdiktat auf diesem Gerät nicht verfügbar"
)

val ChineseStrings = TranslationStrings(
    navCalls = "通话",
    navAssistant = "AI 助理",
    navAgenda = "日程",
    navTasks = "待办",
    navSettings = "设置",
    appTitle = "Intelligent Calls",
    callsTitle = "智能通话",
    callsSubtitle = "原生通话录音与实时转写",
    assistantTitle = "AI 智能助理",
    assistantSubtitle = "实时 CRM 与通话智能分析",
    agendaTitle = "日程与预约",
    agendaSubtitle = "AI 自动提取的日历事件",
    tasksTitle = "待办事项",
    tasksSubtitle = "同步的企业任务清单",
    settingsTitle = "系统设置",
    settingsSubtitle = "个人资料、多语言、主题与数据合规",
    callSummary = "通话智能摘要",
    audioTranscript = "录音文字转写",
    detectedAppointment = "检测到的预约",
    validateSummary = "确认摘要",
    editSummary = "编辑摘要",
    confirmAppointment = "确认日程",
    dismissAppointment = "忽略",
    noSpeechDetected = "此录音中未检测到清晰语音。",
    loadingAnalysis = "正在加载智能分析...",
    retry = "重试",
    lowConfidenceWarning = "AI 置信度较低 (< 60%)",
    lowConfidenceSubtitle = "请检查并核对摘要或会议预约信息。",
    incomingCall = "来电",
    outgoingCall = "去电",
    dialNumber = "请输入电话号码...",
    startCall = "拨打",
    contactsList = "通讯录",
    allCalls = "所有通话",
    historyTab = "通话记录",
    contactsTab = "联系人",
    aiConsentTitle = "AI 转写与智能分析",
    aiConsentActive = "已开启：通话将自动转写并生成智能摘要",
    aiConsentInactive = "已停用：普通通话录音",
    searchContactPlaceholder = "搜索联系人...",
    chatPlaceholder = "询问有关通话、待办或联系人的信息...",
    sendButton = "发送",
    chatGreeting = "您好！我是您的智能通话助理。今天有什么可以帮您？",
    chatAnalyzing = "助理正在分析通话数据...",
    newChat = "新建对话",
    chatHistory = "对话记录",
    addTask = "新建待办",
    taskTitlePlaceholder = "任务描述...",
    noTasks = "暂无待办事项。",
    tasksHeader = "AI 识别的任务清单",
    allTasksFilter = "全部",
    pendingTasksFilter = "进行中",
    completedTasksFilter = "已完成",
    noAppointments = "暂无预约日程。",
    addAppointment = "添加日程",
    agendaHeader = "日程安排与预约",
    agendaClockSubtitle = "AI 智能同步日程",
    profileTab = "个人资料与偏好",
    advancedTab = "高级设置",
    languageSection = "多语言与 AI 引擎",
    languageSubtitle = "Whisper 转写、智能摘要与对话助理",
    themeSection = "外观与主题",
    themeSubtitle = "自定义界面显示模式",
    themeDark = "深色模式",
    themeLight = "浅色模式",
    themeSystem = "跟随系统",
    autoRecordCalls = "自动通话录音",
    hqAudio = "高清音频录制 (AAC HD)",
    serverUrl = "服务器地址",
    save = "保存",
    logout = "退出登录",
    changePassword = "修改密码",
    editProfile = "编辑资料",
    gdprVoiceExport = "导出语音数据",
    gdprAllExport = "导出全部合规数据",
    gdprDeleteVoice = "永久清除语音数据",
    callHistoryAll = "全部",
    callHistoryMissed = "未接",
    callHistoryWithSummary = "带摘要",
    callHistoryEmpty = "历史记录中没有通话",
    callHistorySynchronized = "已同步",
    planAppointment = "安排预约日程",
    appointmentTitlePlaceholder = "会议标题...",
    today = "今天",
    tomorrow = "明天",
    afterTomorrow = "后天",
    oneWeek = "+1周",
    calendarPicker = "📅 日历...",
    dayLabel = "日期:",
    hourLabel = "时间:",
    recordPrefsSection = "录音和通话偏好设置",
    autoRecordDesc = "接听时自动录音",
    hdAudioWav = "高清音频格式 (16kHz WAV)",
    hqAudioDesc = "Whisper和Deepgram的最佳精度",
    aiEnginesSection = "AI引擎和API密钥",
    aiEnginesSubtitle = "Groq, Deepgram STT, OpenAI & Whisper",
    activePipeline = "活动管道",
    saveAiApiKeys = "保存AI API密钥",
    cloudTelephonySection = "云通信与多运营商VoIP",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunk",
    shizukuSection = "SHIZUKU API — ADB提权",
    serverConfigSection = "后端服务器配置",
    gdprSection = "数据隐私与合规",
    exportGdpr = "导出我的数据 (GDPR第15条)",
    deleteVoiceOnly = "仅删除语音录音",
    deleteAccount = "删除我的账户和数据",
    testServer = "测试",
    saveServer = "保存",
    close = "关闭",
    validate = "确认",
    delete = "删除",
    active = "活动",
    open = "打开",
    noChatRecorded = "没有记录的对话。",
    audioVault = "录音保险箱",
    noAudioRecordings = "暂无录音文件",
    playingAudio = "正在播放...",
    priorityLabel = "优先级:",
    priorityUrgent = "紧急",
    priorityImportant = "重要",
    priorityNormal = "普通",
    detectedByAi = "AI 智能提取 · Intelligent Calls",
    shareRecording = "分享录音",
    gdprVoiceConsentDesc = "语音数据授权与分析",
    dialCallTitle = "拨打电话",
    selectContactToCall = "选择联系人以开始通话:",
    noContactsFound = "未找到联系人",
    connectingStatus = "正在连接...",
    onCallAiActive = "正在通话中 - AI 实时转写已开启",
    onCallPlain = "正在通话中 (普通 VoIP)",
    muteLabel = "静音",
    unmuteLabel = "取消静音",
    speakerLabel = "扬声器",
    receiverLabel = "听筒",
    listeningStatus = "正在聆听...",
    waitingForSpeech = "等待语音输入...",
    endCallLabel = "挂断",
    callDisconnected = "通话已结束",
    callError = "通话发生错误",
    aiSettingsDescription = "配置您的专属 API 密钥以启用高精度语音转写与智能摘要:",
    groqApiKeyLabel = "Groq API 密钥",
    deepgramApiKeyLabel = "Deepgram API 密钥 (STT)",
    openAiApiKeyLabel = "OpenAI / Claude API 密钥",
    sttModelLabel = "语音转文字模型 (STT):",
    llmModelLabel = "摘要与日程提取 LLM 模型:",
    voipSelectProviderLabel = "选择云通信 VoIP 服务商以启用双向高清录音:",
    virtualNumberLabel = "虚拟号码 / 线路 (+33...)",
    saveVoipCredentials = "保存 VoIP 配置",
    shizukuStatusConnected = "Shizuku 已连接 (ADB 权限已激活)",
    shizukuStatusRequired = "检测到 Shizuku (需要授权)",
    shizukuStatusStopped = "未检测到 Shizuku / 服务已停止",
    authorizeShizuku = "授权 Shizuku",
    serverUrlLabel = "服务器地址 (例: http://127.0.0.1:8000)",
    usbLocalMode = "USB 本地",
    wifiNetworkMode = "Wi-Fi 局域网",
    gdprNoticeText = "根据数据保护法规范，您拥有访问、导出及彻底删除个人数据的权利。",
    deleteAccountWarning = "您的账户、所有联系人、通话记录、录音及摘要将被永久删除且无法恢复。",
    voiceDictationNotAvailable = "当前设备不支持语音听写"
)

val JapaneseStrings = TranslationStrings(
    navCalls = "通話",
    navAssistant = "AI 助手",
    navAgenda = "予定",
    navTasks = "タスク",
    navSettings = "設定",
    appTitle = "Intelligent Calls",
    callsTitle = "通話インテリジェンス",
    callsSubtitle = "通話録音とリアルタイム文字起こし",
    assistantTitle = "AI アシスタント",
    assistantSubtitle = "リアルタイム CRM・通話分析",
    agendaTitle = "予定表・ミーティング",
    agendaSubtitle = "AI によって抽出されたカレンダー予定",
    tasksTitle = "タスク一覧",
    tasksSubtitle = "同期されたアクションアイテム",
    settingsTitle = "設定",
    settingsSubtitle = "プロフィール、言語、テーマ、VoIP、データ保護",
    callSummary = "通話要約",
    audioTranscript = "音声文字起こし",
    detectedAppointment = "検出された予定",
    validateSummary = "要約を承認",
    editSummary = "要約を編集",
    confirmAppointment = "予定を確定",
    dismissAppointment = "スキップ",
    noSpeechDetected = "録音から明確な音声を検出できませんでした。",
    loadingAnalysis = "AI 分析を読み込み中...",
    retry = "再試行",
    lowConfidenceWarning = "AI の信頼度スコアが低いです (< 60%)",
    lowConfidenceSubtitle = "要約または予定の詳細を確認および調整してください。",
    incomingCall = "着信",
    outgoingCall = "発信",
    dialNumber = "電話番号を入力...",
    startCall = "発信",
    contactsList = "連絡先",
    allCalls = "すべての通話",
    historyTab = "通話履歴",
    contactsTab = "連絡先",
    aiConsentTitle = "AI 文字起こしと分析",
    aiConsentActive = "有効: 通話が自動で文字起こし・要約されます",
    aiConsentInactive = "無効: 通常の通話",
    searchContactPlaceholder = "連絡先を検索...",
    chatPlaceholder = "通話、タスク、連絡先について質問...",
    sendButton = "送信",
    chatGreeting = "こんにちは！Intelligent Calls AI アシスタントです。何かお手伝いできますか？",
    chatAnalyzing = "アシスタントが通話を分析中...",
    newChat = "新規",
    chatHistory = "履歴",
    addTask = "タスクを追加",
    taskTitlePlaceholder = "タスクの説明...",
    noTasks = "タスクはありません。",
    tasksHeader = "AI が検出したタスク",
    allTasksFilter = "すべて",
    pendingTasksFilter = "進行中",
    completedTasksFilter = "完了済み",
    noAppointments = "予定はありません。",
    addAppointment = "予定を追加",
    agendaHeader = "予定表・ミーティング",
    agendaClockSubtitle = "AI 同期カレンダー",
    profileTab = "プロフィールと設定",
    advancedTab = "詳細設定",
    languageSection = "言語と AI インテリジェンス",
    languageSubtitle = "Whisper 文字起こし、AI 要約、チャットボット",
    themeSection = "テーマと外観",
    themeSubtitle = "表示モードのカスタマイズ",
    themeDark = "ダーク",
    themeLight = "ライト",
    themeSystem = "システム連動",
    autoRecordCalls = "通話の自動録音",
    hqAudio = "高音質録音 (AAC HD)",
    serverUrl = "サーバー URL",
    save = "保存",
    logout = "ログアウト",
    changePassword = "パスワード変更",
    editProfile = "プロフィール編集",
    gdprVoiceExport = "音声データのエクスポート",
    gdprAllExport = "全データのエクスポート",
    gdprDeleteVoice = "音声データの完全消去",
    callHistoryAll = "すべて",
    callHistoryMissed = "不在着信",
    callHistoryWithSummary = "要約あり",
    callHistoryEmpty = "通話履歴はありません",
    callHistorySynchronized = "同期済み",
    planAppointment = "予定をスケジュール",
    appointmentTitlePlaceholder = "会議のタイトル...",
    today = "今日",
    tomorrow = "明日",
    afterTomorrow = "明後日",
    oneWeek = "+1週間",
    calendarPicker = "📅 カレンダー...",
    dayLabel = "日:",
    hourLabel = "時間:",
    recordPrefsSection = "録音と通話の設定",
    autoRecordDesc = "応答時に自動録音",
    hdAudioWav = "HDオーディオ形式 (16kHz WAV)",
    hqAudioDesc = "WhisperとDeepgramの最適な精度",
    aiEnginesSection = "AIエンジンとAPIキー",
    aiEnginesSubtitle = "Groq, Deepgram STT, OpenAI & Whisper",
    activePipeline = "アクティブなパイプライン",
    saveAiApiKeys = "AI APIキーを保存",
    cloudTelephonySection = "クラウド電話 & マルチVoIP",
    cloudTelephonySubtitle = "Twilio, Telnyx, Plivo, Vonage & SIP Trunk",
    shizukuSection = "SHIZUKU API — 昇格したADB権限",
    serverConfigSection = "バックエンドサーバー構成",
    gdprSection = "GDPRおよびデータ保護",
    exportGdpr = "マイデータをエクスポート (GDPR第15条)",
    deleteVoiceOnly = "音声録音のみを削除",
    deleteAccount = "アカウントとすべてのデータを削除",
    testServer = "テスト",
    saveServer = "保存",
    close = "閉じる",
    validate = "確定",
    delete = "削除",
    active = "アクティブ",
    open = "開く",
    noChatRecorded = "会話は記録されていません。",
    audioVault = "音声保管庫",
    noAudioRecordings = "音声録音はまだありません",
    playingAudio = "再生中...",
    priorityLabel = "優先度:",
    priorityUrgent = "緊急",
    priorityImportant = "重要",
    priorityNormal = "通常",
    detectedByAi = "AI による自動検出 · Intelligent Calls",
    shareRecording = "録音を共有",
    gdprVoiceConsentDesc = "音声データの利用と分析への同意",
    dialCallTitle = "発信する",
    selectContactToCall = "発信する連絡先を選択してください:",
    noContactsFound = "登録されている連絡先はありません",
    connectingStatus = "接続中...",
    onCallAiActive = "通話中 - AI リアルタイム文字起こし有効",
    onCallPlain = "通話中 (通常の VoIP)",
    muteLabel = "消音",
    unmuteLabel = "消音解除",
    speakerLabel = "スピーカー",
    receiverLabel = "受話口",
    listeningStatus = "音声を聞き取り中...",
    waitingForSpeech = "発話を待機中...",
    endCallLabel = "終了",
    callDisconnected = "通話を終了しました",
    callError = "通話エラー",
    aiSettingsDescription = "音声文字起こしと自動要約を有効にするための API キーを設定します:",
    groqApiKeyLabel = "Groq API キー",
    deepgramApiKeyLabel = "Deepgram API キー (STT)",
    openAiApiKeyLabel = "OpenAI / Claude API キー",
    sttModelLabel = "音声認識モデル (STT):",
    llmModelLabel = "要約・予定抽出 LLM エンジン:",
    voipSelectProviderLabel = "双方向 HD 録音用のクラウド VoIP プロバイダーを選択:",
    virtualNumberLabel = "仮想番号 / ゲートウェイ (+33...)",
    saveVoipCredentials = "VoIP 設定を保存",
    shizukuStatusConnected = "Shizuku 接続済み (ADB 権限有効)",
    shizukuStatusRequired = "Shizuku 検出 (権限が必要です)",
    shizukuStatusStopped = "Shizuku 未検出 / サービス停止",
    authorizeShizuku = "Shizuku を許可",
    serverUrlLabel = "サーバー URL (例: http://127.0.0.1:8000)",
    usbLocalMode = "USB ローカル",
    wifiNetworkMode = "Wi-Fi ネットワーク",
    gdprNoticeText = "データ保護規則に従い、ユーザーはデータの照会、エクスポート、削除の権利を有します。",
    deleteAccountWarning = "アカウント、連絡先、通話履歴、録音データ、要約が完全に消去されます。",
    voiceDictationNotAvailable = "この端末では音声入力が利用できません"
)

fun getAppStrings(languageCode: String?): TranslationStrings {
    return when (languageCode?.lowercase()?.take(2)) {
        "fr" -> FrenchStrings
        "ar" -> ArabicStrings
        "es" -> SpanishStrings
        "de" -> GermanStrings
        "zh" -> ChineseStrings
        "ja" -> JapaneseStrings
        else -> EnglishStrings
    }
}

fun getAppLocale(languageCode: String?): Locale {
    return when (languageCode?.lowercase()?.take(2)) {
        "fr" -> Locale.FRENCH
        "ar" -> Locale("ar")
        "es" -> Locale("es")
        "de" -> Locale.GERMAN
        "zh" -> Locale.CHINESE
        "ja" -> Locale.JAPANESE
        else -> Locale.ENGLISH
    }
}
'''

target_path = r"c:\Users\khali\OneDrive\Bureau\intelligentCall\IntelligentCalls\app\src\main\java\com\example\appcall\presentation\theme\AppStrings.kt"
with open(target_path, "w", encoding="utf-8") as f:
    f.write(app_strings_content)
print("Updated AppStrings.kt successfully!")
